[functions.iprogsms-hook]
enabled = true
verify_jwt = false
import_map = "./functions/iprogsms-hook/deno.json"
entrypoint = "./functions/iprogsms-hook/index.ts"

[functions.complete-registration]
enabled = true
verify_jwt = true
import_map = "./functions/complete-registration/deno.json"
entrypoint = "./functions/complete-registration/index.ts"

[functions.verify-login]
enabled = true
verify_jwt = false
import_map = "./functions/verify-login/deno.json"
entrypoint = "./functions/verify-login/index.ts"

[functions.request-registration-otp]
enabled = true
verify_jwt = false
import_map = "./functions/request-registration-otp/deno.json"
entrypoint = "./functions/request-registration-otp/index.ts"

[functions.reset-pin]
enabled = true
verify_jwt = true
import_map = "./functions/reset-pin/deno.json"
entrypoint = "./functions/reset-pin/index.ts"

[functions.create-report]
enabled = true
verify_jwt = true
import_map = "./functions/create-report/deno.json"
entrypoint = "./functions/create-report/index.ts"
