import { StyleSheet } from 'react-native';

import { colors, fontSizes, radius, spacing } from '../theme';

// Keep the resident Home experience self-contained while experimenting with Inter.
const homeFonts = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  semibold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
  extrabold: 'Inter_800ExtraBold',
};

export const homeColors = {
  background: colors.background,
  ink: colors.text,
  headingInk: '#10213F',
  border: '#E1E5EC',
  clear: '#56865B',
  accentBlue: '#0F356B',
  evacuation: '#7BA682',
};

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: homeColors.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: homeColors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 126,
  },
  homeScrollView: {
    flex: 1,
  },
  residentStickyHeader: {
    position: 'absolute',
    right: 0,
    left: 0,
    width: '100%',
    overflow: 'hidden',
    zIndex: 10,
    backgroundColor: homeColors.background,
  },
  residentHeaderContent: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  headerBody: {
    paddingBottom: spacing.sm,
  },
  // Resident greeting and account actions.
  greetingRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  greetingCopy: {
    flex: 1,
    minWidth: 0,
  },
  greetingTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: homeColors.ink,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 3,
  },
  locationText: {
    flex: 1,
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    color: '#59657A',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  compactHeaderRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactHeaderTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: homeColors.ink,
  },
  compactHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  notificationButton: {
    width: 38,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 4,
    right: 1,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#E14348',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FBF0E4',
  },
  avatarText: {
    fontFamily: homeFonts.medium,
    fontSize: 17,
    color: homeColors.ink,
  },
  // Resident version of the MDRRMO report queue, filtered by the device location.
  nearbyReportsPanel: {
    width: '100%',
    backgroundColor: colors.white,
  },
  // Mirrors the MDRRMO command map while keeping the content resident-facing.
  nearbyMapHero: {
    width: '100%',
    height: 285,
    overflow: 'hidden',
    backgroundColor: '#E8F1F5',
  },
  nearbyMapFill: {
    ...StyleSheet.absoluteFill,
  },
  // Matches the compact status badge used on the MDRRMO command map.
  nearbyMapCountBadge: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.lg,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  nearbyMapCountDot: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
  },
  nearbyMapCountText: {
    fontFamily: homeFonts.semibold,
    fontSize: 11,
    color: colors.primary,
  },
  nearbyMapPager: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    paddingHorizontal: 2,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  nearbyMapPagerButton: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nearbyMapPagerText: {
    minWidth: 34,
    fontFamily: homeFonts.regular,
    fontSize: 10,
    color: '#526078',
    textAlign: 'center',
  },
  nearbyActiveReportCard: {
    gap: 10,
    paddingHorizontal: spacing.md,
    paddingTop: 12,
    paddingBottom: 0,
    backgroundColor: colors.white,
  },
  nearbyActiveReportTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  nearbyActiveReportCopy: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    gap: 0,
  },
  nearbyActiveReportEyebrow: {
    fontFamily: homeFonts.bold,
    fontSize: fontSizes.sm,
    lineHeight: 16,
  },
  nearbyActiveReportTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: 24,
    lineHeight: 27,
    color: homeColors.headingInk,
  },
  nearbyActiveReportMeta: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    color: '#6D7B92',
  },
  nearbyOpenReportAction: {
    width: 62,
    alignItems: 'center',
    gap: 3,
  },
  nearbyOpenReportCircle: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: homeColors.ink,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 7,
    elevation: 4,
  },
  nearbyOpenReportLabel: {
    fontFamily: homeFonts.semibold,
    fontSize: 9,
    color: homeColors.ink,
    textAlign: 'center',
  },
  nearbyActiveReportQuote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(15, 32, 68, 0.06)',
  },
  nearbyActiveReportQuoteAccent: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 5,
  },
  nearbyActiveReportQuoteMark: {
    width: 28,
    marginTop: -3,
    fontFamily: homeFonts.bold,
    fontSize: 34,
    lineHeight: 36,
    textAlign: 'center',
  },
  nearbyActiveReportQuoteCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  nearbyActiveReportQuoteText: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 20,
    color: homeColors.ink,
  },
  nearbyActiveReportQuoteSource: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.xs,
    color: '#6D7B92',
  },
  nearbyReportsState: {
    minHeight: 172,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xl,
  },
  nearbyReportsStateTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.lg,
    color: homeColors.ink,
    textAlign: 'center',
  },
  nearbyReportsStateText: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
  },
  nearbyReportsRetryButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
  },
  nearbyReportsRetryText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.white,
  },
  nearbyReportsEmptyIcon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Quick-access cards.
  quickAccessSection: {
    width: '100%',
    gap: 6,
    paddingHorizontal: spacing.lg,
    paddingTop: 0,
  },
  quickAccessContent: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
  },
  quickAccessHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 3,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  quickAccessTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.xl,
    color: homeColors.headingInk,
  },
  quickAccessRow: {
    minHeight: 58,
    flexDirection: 'row',
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  quickAccessCard: {
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingHorizontal: 2,
  },
  quickAccessCardBorder: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: '#D9E1EC',
  },
  quickAccessText: {
    fontFamily: homeFonts.semibold,
    fontSize: 10,
    lineHeight: 15,
    color: homeColors.ink,
    textAlign: 'center',
  },

  // Rotating preparedness reminders shown below Quick Access.
  reminderBannerSection: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  reminderBanner: {
    width: '100%',
    aspectRatio: 2.4,
    overflow: 'hidden',
    borderRadius: radius.md,
    backgroundColor: '#EDF3F9',
  },
  reminderBannerImageLayer: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reminderBannerImage: {
    width: '100%',
    height: '100%',
  },
  reminderIndicators: {
    position: 'absolute',
    right: 0,
    bottom: 8,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  reminderIndicator: {
    width: 7,
    height: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 4,
    backgroundColor: 'rgba(15, 32, 68, 0.48)',
  },
  reminderIndicatorActive: {
    width: 9,
    height: 9,
    borderColor: homeColors.ink,
    borderRadius: 5,
    backgroundColor: colors.white,
  },

  // Shared content sections and states.
  contentSection: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
  },
  sectionBlock: {
    marginTop: spacing.xs,
  },
  reminderForYouSection: {
    marginTop: spacing.xs,
  },
  reminderForYouHeader: {
    marginBottom: 2,
  },
  sectionHeaderRow: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  sectionHeadingCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  sectionTitle: {
    flex: 1,
    minWidth: 0,
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.xl,
    color: homeColors.headingInk,
  },
  sectionSubtitle: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    color: colors.textMuted,
  },
  officialUpdatesCarousel: {
    alignSelf: 'center',
  },
  officialUpdatesCarouselContent: {
    gap: 4,
  },
  officialUpdateCardWrap: {
    position: 'relative',
    paddingVertical: spacing.sm,
  },
  officialUpdateCardEmphasis: {
    width: '100%',
  },
  officialUpdateSwipeArrow: {
    position: 'absolute',
    top: 142,
    right: -8,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  officialUpdatesPromptOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(7, 24, 42, 0.48)',
  },
  officialUpdatesPromptCard: {
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    padding: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  officialUpdatesPromptIcon: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    borderRadius: radius.full,
    backgroundColor: '#EAF0F7',
  },
  officialUpdatesPromptTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.lg,
    color: homeColors.ink,
    textAlign: 'center',
  },
  officialUpdatesPromptText: {
    marginTop: spacing.xs,
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
  },
  officialUpdatesPromptPrimaryAction: {
    width: '100%',
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.lg,
    borderRadius: radius.sm,
    backgroundColor: homeColors.ink,
  },
  officialUpdatesPromptPrimaryText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.white,
  },
  officialUpdatesPromptDismissAction: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.xs,
  },
  officialUpdatesPromptDismissText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },
  stateCard: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  stateText: {
    flexShrink: 1,
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
    textAlign: 'center',
  },

  // Official update cards mirror the MDRRMO Barangay Updates treatment.
  officialUpdateCard: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E1E8F2',
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 3,
  },
  officialUpdateMediaFrame: {
    width: '100%',
    height: 190,
    overflow: 'hidden',
    backgroundColor: '#EAF0F7',
  },
  officialUpdateMedia: {
    ...StyleSheet.absoluteFill,
  },
  officialUpdateMediaPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: '#EAF0F7',
  },
  officialUpdateMediaPlaceholderText: {
    fontFamily: homeFonts.medium,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
  },
  officialUpdateMediaLabel: {
    position: 'absolute',
    top: spacing.sm,
    left: spacing.md,
    maxWidth: '78%',
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(7, 24, 42, 0.82)',
  },
  officialUpdateMediaLabelText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.xs,
    color: colors.white,
    textTransform: 'uppercase',
  },
  officialUpdateMediaCount: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(7, 24, 42, 0.82)',
  },
  officialUpdateMediaCountText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.xs,
    color: colors.white,
  },
  officialUpdateCardCopy: {
    gap: 2,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xs,
  },
  officialUpdateTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.lg,
    lineHeight: 23,
    color: homeColors.ink,
  },
  officialUpdateBody: {
    fontFamily: homeFonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: '#526078',
  },
  officialUpdateAction: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    // Preserve its separation from the announcement text while tightening the card bottom.
    marginTop: spacing.xs,
  },
  officialUpdateActionText: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },

  // Compact, freely scrollable preparedness cards beneath official updates.
  reminderForYouCarousel: {
    width: '100%',
  },
  reminderForYouCarouselContent: {
    gap: spacing.sm,
    paddingRight: spacing.lg,
  },
  reminderForYouCard: {
    width: 184,
    overflow: 'hidden',
    borderRadius: 4,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 7,
    elevation: 2,
  },
  reminderForYouImage: {
    width: '100%',
    height: 104,
  },
  reminderForYouCopy: {
    gap: 2,
    padding: spacing.sm,
  },
  reminderForYouTitle: {
    fontFamily: homeFonts.semibold,
    fontSize: fontSizes.sm,
    color: homeColors.headingInk,
  },
  reminderForYouDescription: {
    fontFamily: homeFonts.regular,
    fontSize: 11,
    lineHeight: 15,
    color: colors.textMuted,
  },

  // Kept for the existing nearby-report loading animation.
  nearbyReportAnimationWrap: {
    width: 128,
    height: 117,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nearbyReportAnimation: {
    width: 128,
    height: 117,
  },
  welcomeOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(15, 32, 68, 0.55)',
  },
});
