import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const homeColors = {
  background: colors.background,
  ink: '#20252C',
  border: '#E7E3DE',
  clear: '#56865B',
  warning: '#D97706',
  accentBlue: '#378FE7',
  searchFill: '#E8F4FC',
};

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: homeColors.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: homeColors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 132,
  },
  residentStickyHeader: {
    width: '100%',
    backgroundColor: homeColors.background,
    zIndex: 10,
  },
  residentHeaderContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
  },

  // Header and resident identity
  heroSection: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
  },
  headerBody: {
    paddingBottom: spacing.md,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  greetingCopy: {
    flex: 1,
    minWidth: 0,
  },
  greetingTitle: {
    fontFamily: fonts.bold,
    fontSize: 29,
    lineHeight: 36,
    letterSpacing: -0.8,
    color: homeColors.ink,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: 4,
  },
  locationText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: homeColors.ink,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  notificationButton: {
    width: 36,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 5,
    right: 2,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.secondary,
    borderWidth: 1.5,
    borderColor: homeColors.background,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FBF1E5',
  },
  avatarText: {
    fontFamily: fonts.medium,
    fontSize: 21,
    color: homeColors.ink,
  },
  nearbyReportBlock: {
    width: '100%',
    alignItems: 'center',
    marginTop: spacing.xl,
  },
  nearbyReportAnimationWrap: {
    width: 128,
    height: 117,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nearbyReportAnimation: {
    width: 128,
    height: 117,
  },
  areaStatusText: {
    marginTop: spacing.xs,
    paddingHorizontal: spacing.md,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: homeColors.ink,
    textAlign: 'center',
  },
  searchBar: {
    minHeight: 48,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.sm + spacing.xs,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.md,
    backgroundColor: homeColors.searchFill,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: spacing.sm + 2,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: homeColors.ink,
    textAlign: 'left',
  },
  searchResultsCard: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  searchResultRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchResultDivider: {
    borderBottomWidth: 1,
    borderBottomColor: homeColors.border,
  },
  searchResultCopy: {
    flex: 1,
    minWidth: 0,
  },
  searchResultTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },
  searchResultType: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: colors.textMuted,
  },

  // Shared section structure
  contentSection: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
  },
  sectionBlock: {
    marginTop: spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  municipalHeaderRow: {
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    flexShrink: 1,
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.4,
    color: homeColors.ink,
  },
  sectionLink: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.md,
    color: homeColors.accentBlue,
  },
  quickAccessSpacer: {
    height: spacing.lg,
  },
  quickAccessSection: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  quickAccessContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: spacing.sm + spacing.xs,
    paddingVertical: spacing.xs,
  },
  stateCard: {
    minHeight: 80,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  stateText: {
    flexShrink: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
    textAlign: 'center',
  },

  // Municipal and barangay update card
  updateCard: {
    minHeight: 116,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  updateSeal: {
    width: 70,
    height: 70,
  },
  updateContent: {
    flex: 1,
    minWidth: 0,
  },
  updateLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    color: homeColors.accentBlue,
  },
  updateTitle: {
    marginTop: 2,
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    lineHeight: 22,
    color: homeColors.ink,
  },
  updateMeta: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
  },
  updateBody: {
    marginTop: spacing.xs,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    color: homeColors.ink,
  },
  updateChevron: {
    color: homeColors.ink,
  },
  featuredUpdateCard: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    shadowColor: homeColors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  featuredUpdateContent: {
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  featuredOfficialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  featuredOfficialBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.full,
    backgroundColor: homeColors.searchFill,
  },
  featuredOfficialBadgeText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xs,
    color: homeColors.accentBlue,
  },
  featuredOfficeLabel: {
    flexShrink: 1,
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
  },
  featuredMainRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 0,
  },
  featuredCopy: {
    flex: 1,
    minWidth: 0,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
  },
  featuredThumb: {
    width: 112,
    minHeight: 148,
    flexShrink: 0,
    alignSelf: 'stretch',
    marginTop: spacing.sm,
    marginRight: spacing.sm,
    marginBottom: spacing.sm,
    overflow: 'hidden',
    borderRadius: radius.sm,
    backgroundColor: '#F4F7FA',
  },
  featuredThumbMedia: {
    ...StyleSheet.absoluteFillObject,
  },
  featuredThumbFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F4F7FA',
  },
  featuredVideoBadge: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: 'rgba(15, 32, 68, 0.72)',
  },
  featuredUpdateTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    lineHeight: 21,
    letterSpacing: -0.3,
    color: homeColors.ink,
  },
  featuredUpdateBody: {
    marginTop: spacing.xs,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colors.textMuted,
  },
  featuredDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.sm,
  },
  featuredDateIcon: {
    marginTop: 1,
  },
  featuredUpdateDate: {
    flex: 1,
    minWidth: 0,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
  },
  featuredReadMoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginTop: 6,
  },
  featuredReadMoreText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: homeColors.accentBlue,
  },
  featuredActionsRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: homeColors.border,
  },
  featuredActionButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
  },
  featuredActionDivider: {
    width: 1,
    height: 22,
    backgroundColor: homeColors.border,
  },
  featuredActionIcon: {
    color: homeColors.ink,
  },
  featuredActionIconActive: {
    color: colors.primary,
  },
  featuredActionCount: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },
  featuredActionCountActive: {
    fontFamily: fonts.medium,
    color: colors.primary,
  },

  // Quick-access cards
  quickAccessRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  quickAccessCard: {
    flex: 0,
    minWidth: 0,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
  },
  quickAccessIcon: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickAccessText: {
    marginTop: 4,
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 12,
    color: homeColors.ink,
    textAlign: 'center',
  },

  // Nearby report list + live map
  nearbyPanel: {
    minHeight: 210,
    flexDirection: 'row',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: homeColors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  nearbyPanelCompact: {
    minHeight: 350,
    flexDirection: 'column',
  },
  nearbyReportList: {
    flex: 0.95,
    minWidth: 0,
    paddingHorizontal: spacing.sm,
  },
  nearbyReportListCompact: {
    flex: 0,
    minHeight: 195,
  },
  nearbyReportRow: {
    flex: 1,
    minHeight: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 4,
    paddingVertical: 8,
    marginHorizontal: -4,
    borderRadius: radius.md,
  },
  nearbyReportRowFocused: {
    backgroundColor: '#F2F7FD',
  },
  nearbyReportDivider: {
    borderBottomWidth: 1,
    borderBottomColor: homeColors.border,
  },
  reportThumbnail: {
    width: 72,
    height: 76,
    flexShrink: 0,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: '#F1F3F5',
  },
  reportThumbnailImage: {
    width: '100%',
    height: '100%',
  },
  reportSummary: {
    flex: 1,
    minWidth: 0,
  },
  reportTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.md,
    lineHeight: 18,
    color: homeColors.ink,
  },
  reportLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 5,
  },
  reportLocationIcon: {
    opacity: 0.65,
  },
  reportDistance: {
    marginTop: 3,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },
  reportAddress: {
    flex: 1,
    minWidth: 0,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: homeColors.ink,
  },
  reportTime: {
    marginTop: 4,
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: colors.textMuted,
  },
  nearbyState: {
    flex: 1,
    minHeight: 170,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
  },
  nearbyMapWrap: {
    flex: 1.05,
    minWidth: 0,
    borderLeftWidth: 1,
    borderLeftColor: homeColors.border,
  },
  nearbyMapWrapCompact: {
    flex: 1,
    minHeight: 150,
    borderLeftWidth: 0,
    borderTopWidth: 1,
    borderTopColor: homeColors.border,
  },
  nearbyMap: {
    flex: 1,
    minHeight: 150,
    backgroundColor: colors.background,
  },
  // Shared by the existing post-registration welcome modal.
  welcomeOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(15, 32, 68, 0.55)',
  },
});
