import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

const executiveBlue = '#0B2340';
const mutedBlue = '#5A718B';
const cardShadow = '#0B1E30';

export const mayorBriefStyles = StyleSheet.create({
  content: {
    backgroundColor: colors.background,
  },
  mapHero: {
    width: '100%',
    overflow: 'hidden',
    backgroundColor: '#071827',
  },
  heroMapFill: {
    ...StyleSheet.absoluteFill,
  },
  heroTopBlueFade: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
  },
  heroContent: {
    ...StyleSheet.absoluteFill,
    paddingHorizontal: spacing.md,
    paddingBottom: 14,
  },
  mapFrame: {
    flex: 1,
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(218, 232, 241, 0.72)',
    borderRadius: 17,
    backgroundColor: 'rgba(7, 24, 39, 0.06)',
  },
  heroScopeCard: {
    width: '78%',
    minWidth: 280,
    maxWidth: 300,
    alignSelf: 'flex-start',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.38)',
    borderRadius: 15,
    backgroundColor: 'rgba(7, 24, 39, 0.56)',
  },
  scopeSegment: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 6,
  },
  scopeDivider: {
    width: 1,
    height: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.44)',
  },
  scopeValue: {
    flex: 1,
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: colors.white,
  },
  heroSituation: {
    flex: 1,
    padding: 10,
  },
  heroLoadingRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  heroLoadingText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: colors.white,
    textAlign: 'center',
  },
  heroError: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  heroRetryText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: '#71C8FF',
  },
  situationHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  situationAccent: {
    width: 5,
    height: 22,
    borderRadius: radius.full,
    backgroundColor: '#48B4F5',
  },
  situationLabel: {
    fontFamily: fonts.bold,
    fontSize: 18,
    letterSpacing: -0.4,
    color: colors.white,
  },
  situationCount: {
    marginTop: 1,
    fontFamily: fonts.extrabold,
    fontSize: 54,
    lineHeight: 57,
    letterSpacing: -2,
    color: colors.white,
  },
  situationCaption: {
    marginTop: -4,
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 22,
    letterSpacing: -0.5,
    color: colors.white,
  },
  barangayPill: {
    alignSelf: 'flex-start',
    minHeight: 31,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: radius.full,
    backgroundColor: 'rgba(7, 24, 39, 0.4)',
  },
  barangayPillText: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: colors.white,
  },
  situationFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginTop: 'auto',
  },
  updatedRow: {
    flexShrink: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingBottom: 7,
  },
  situationUpdated: {
    flexShrink: 1,
    fontFamily: fonts.regular,
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.86)',
  },
  situationButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 15,
    borderRadius: 11,
    backgroundColor: '#338FD0',
    shadowColor: '#06131F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  situationButtonText: {
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: colors.white,
  },
  dashboardBody: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
    backgroundColor: colors.background,
  },
  warningCard: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 13,
    borderRadius: radius.md,
    backgroundColor: '#FFF5F3',
  },
  warningText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
    color: colors.text,
  },
  verificationBanner: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 13,
    backgroundColor: '#FFF0EF',
  },
  verificationCountCircle: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#DD3E43',
  },
  verificationCount: {
    fontFamily: fonts.extrabold,
    fontSize: 18,
    color: colors.white,
  },
  verificationDivider: {
    width: 1,
    height: 32,
    backgroundColor: 'rgba(192, 80, 80, 0.24)',
  },
  verificationCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  verificationTitle: {
    fontFamily: fonts.bold,
    fontSize: 13,
    lineHeight: 17,
    color: executiveBlue,
  },
  verificationSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 13,
    color: mutedBlue,
  },
  verificationButton: {
    minWidth: 82,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
    borderRadius: 8,
    backgroundColor: '#102A45',
  },
  verificationButtonText: {
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: colors.white,
  },
  activityCard: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#EEF8F7',
  },
  activityIconWrap: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: '#3CA78F',
  },
  activityCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    gap: 2,
  },
  activityTitle: {
    fontFamily: fonts.bold,
    fontSize: 13,
    color: executiveBlue,
  },
  activitySubtitle: {
    fontFamily: fonts.regular,
    fontSize: 10,
    color: mutedBlue,
  },
  activityLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  linkText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: colors.primary,
  },
  dashboardSection: {
    gap: 6,
  },
  sectionHeader: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
  },
  sectionTitleGroup: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 9,
  },
  sectionTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 19,
    lineHeight: 23,
    letterSpacing: -0.5,
    color: executiveBlue,
  },
  sectionEyebrow: {
    flexShrink: 1,
    fontFamily: fonts.medium,
    fontSize: 8,
    letterSpacing: 1.15,
    color: mutedBlue,
    textAlign: 'right',
  },
  quickViewRow: {
    flexDirection: 'row',
    gap: 5,
  },
  quickViewCard: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    minHeight: 80,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 7,
    borderRadius: 13,
  },
  quickViewCardWide: {
    flex: 1.24,
  },
  quickViewCardPrimary: {
    backgroundColor: '#102E4B',
  },
  quickViewCardBlue: {
    backgroundColor: '#EAF6FC',
  },
  quickViewCardSlate: {
    backgroundColor: '#EEF2F4',
  },
  quickViewCardMint: {
    backgroundColor: '#EAF8F4',
  },
  quickViewTopRow: {
    position: 'relative',
    width: '100%',
    height: 31,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickViewChevron: {
    position: 'absolute',
    right: 0,
  },
  quickViewIconWrap: {
    position: 'relative',
    width: 29,
    height: 29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickViewBadge: {
    position: 'absolute',
    top: -8,
    right: -10,
    minWidth: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: radius.full,
    backgroundColor: '#DD3E43',
  },
  quickViewBadgeText: {
    fontFamily: fonts.bold,
    fontSize: 9,
    color: colors.white,
  },
  quickViewLabel: {
    fontFamily: fonts.bold,
    fontSize: 12,
    color: executiveBlue,
    textAlign: 'center',
  },
  quickViewSubtitle: {
    minHeight: 22,
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 11,
    color: mutedBlue,
    textAlign: 'center',
  },
  quickViewTextLight: {
    color: colors.white,
  },
  quickViewSubtitleLight: {
    color: 'rgba(255, 255, 255, 0.76)',
  },
  sectionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 2,
  },
  sectionLinkText: {
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: colors.primary,
  },
  briefingRow: {
    gap: 8,
    paddingRight: spacing.md,
  },
  briefingCard: {
    height: 112,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DCE5EB',
    borderRadius: 14,
    backgroundColor: '#DDE9EE',
    shadowColor: cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  briefingImage: {
    flex: 1,
  },
  briefingImageStyle: {
    resizeMode: 'cover',
  },
  briefingShade: {
    ...StyleSheet.absoluteFill,
  },
  briefingContent: {
    position: 'absolute',
    right: 9,
    bottom: 8,
    left: 9,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
  },
  briefingTitle: {
    fontFamily: fonts.bold,
    fontSize: 13,
    lineHeight: 17,
    color: colors.white,
  },
  briefingSubtitle: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.82)',
  },
  briefingArrow: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.38)',
    borderRadius: 14,
    backgroundColor: 'rgba(9, 29, 45, 0.38)',
  },
  affectedCountBadge: {
    position: 'absolute',
    top: 11,
    alignSelf: 'center',
    minWidth: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 17,
    backgroundColor: '#D64247',
    shadowColor: '#8A1F24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.32,
    shadowRadius: 5,
    elevation: 3,
  },
  affectedCountText: {
    fontFamily: fonts.bold,
    fontSize: 11,
    color: colors.white,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15, 23, 42, 0.46)',
  },
  scopeSheet: {
    maxHeight: '86%',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.white,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#C7CDD6',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sheetHeaderCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  sheetEyebrow: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    letterSpacing: 0.5,
    color: mutedBlue,
  },
  sheetTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 27,
    color: colors.text,
  },
  sheetClose: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: '#F2F5F7',
  },
  sheetLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  filterChip: {
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.full,
  },
  filterChipActive: {
    borderColor: executiveBlue,
    backgroundColor: executiveBlue,
  },
  filterChipText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  filterChipTextActive: {
    color: colors.white,
  },
  barangayList: {
    maxHeight: 260,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  sheetOption: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetOptionText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  sheetOptionTextActive: {
    fontFamily: fonts.semibold,
    color: colors.primary,
  },
  applyButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: colors.primary,
  },
  applyButtonText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.white,
  },
});
