import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

const executiveBlue = '#0B2340';
const mutedBlue = '#5A718B';
const cardShadow = '#0B1E30';

export const mayorBriefStyles = StyleSheet.create({
  content: {
    backgroundColor: colors.background,
  },
  // Keep the Brief header separate from the map, matching the MDRRMO Command layout.
  briefStickyHeader: {
    zIndex: 10,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
  },
  mapHero: {
    width: '100%',
    height: 285,
    overflow: 'hidden',
    backgroundColor: '#E8F1F5',
  },
  mapFill: {
    ...StyleSheet.absoluteFill,
  },
  mapReportBadge: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
    paddingHorizontal: 8,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  mapReportBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.escalated,
  },
  mapReportBadgeText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: colors.escalated,
  },
  mapPager: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.md,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    paddingHorizontal: 2,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  mapPagerButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapPagerText: {
    minWidth: 34,
    fontFamily: fonts.regular,
    fontSize: 10,
    color: '#526078',
    textAlign: 'center',
  },
  dashboardBody: {
    width: '100%',
    alignSelf: 'center',
    gap: 0,
    paddingTop: 0,
    backgroundColor: colors.background,
  },
  stateBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
  },
  warningCard: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    paddingHorizontal: 13,
    borderRadius: radius.md,
    backgroundColor: '#FFF5F3',
  },
  warningText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
    color: colors.text,
  },
  dashboardSection: {
    gap: 8,
    paddingHorizontal: spacing.lg,
    paddingTop: 12,
    paddingBottom: spacing.sm,
  },
  sectionHeader: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
  },
  sectionTitleGroup: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 9,
  },
  sectionTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 19,
    lineHeight: 23,
    letterSpacing: -0.5,
    color: executiveBlue,
  },
  sectionEyebrow: {
    flexShrink: 1,
    fontFamily: fonts.medium,
    fontSize: 8,
    letterSpacing: 1.15,
    color: mutedBlue,
    textAlign: 'right',
  },
  quickViewRow: {
    flexDirection: 'row',
    minHeight: 58,
    paddingBottom: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  quickViewCard: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingHorizontal: 2,
  },
  quickViewCardDivider: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: '#D9E1EC',
  },
  quickViewIconWrap: {
    position: 'relative',
    width: 30,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickViewBadge: {
    position: 'absolute',
    top: -8,
    right: -10,
    minWidth: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: radius.full,
    backgroundColor: '#DD3E43',
  },
  quickViewBadgeText: {
    fontFamily: fonts.bold,
    fontSize: 9,
    color: colors.white,
  },
  quickViewLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 15,
    color: colors.text,
    textAlign: 'center',
  },
  sectionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 2,
  },
  sectionLinkText: {
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: colors.primary,
  },
  briefingRow: {
    gap: 8,
    paddingRight: spacing.md,
    paddingVertical: spacing.xs,
  },
  briefingCard: {
    height: 112,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DCE5EB',
    borderRadius: 14,
    backgroundColor: '#DDE9EE',
    shadowColor: cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  briefingImage: {
    flex: 1,
  },
  briefingImageStyle: {
    resizeMode: 'cover',
  },
  briefingShade: {
    ...StyleSheet.absoluteFill,
  },
  briefingContent: {
    position: 'absolute',
    right: 9,
    bottom: 8,
    left: 9,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
  },
  briefingTitle: {
    fontFamily: fonts.bold,
    fontSize: 13,
    lineHeight: 17,
    color: colors.white,
  },
  briefingSubtitle: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.82)',
  },
  briefingArrow: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.38)',
    borderRadius: 14,
    backgroundColor: 'rgba(9, 29, 45, 0.38)',
  },
  affectedCountBadge: {
    position: 'absolute',
    top: 11,
    alignSelf: 'center',
    minWidth: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 17,
    backgroundColor: '#D64247',
    shadowColor: '#8A1F24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.32,
    shadowRadius: 5,
    elevation: 3,
  },
  affectedCountText: {
    fontFamily: fonts.bold,
    fontSize: 11,
    color: colors.white,
  },
});
