import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const mayorBriefStyles = StyleSheet.create({
  content: { paddingHorizontal: spacing.lg, paddingTop: spacing.sm, gap: spacing.lg, backgroundColor: colors.white },
  eyebrow: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: '#53617A', letterSpacing: 0.5 },
  scopeCard: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.white },
  scopeCopy: { flex: 1, gap: 5 },
  scopeValue: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
  stateCard: { minHeight: 140, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.lg, borderRadius: radius.xl, backgroundColor: colors.primaryLight },
  stateTitle: { fontFamily: fonts.bold, fontSize: fontSizes.lg, color: colors.text, textAlign: 'center' },
  stateText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, lineHeight: 20, color: colors.textMuted, textAlign: 'center' },
  warningCard: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: '#FFF7ED' },
  warningText: { flex: 1, fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  mapCard: { overflow: 'hidden', borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.white, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.1, shadowRadius: 14, elevation: 4 },
  mapHeaderOverlay: { minHeight: 108, flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, padding: spacing.md, backgroundColor: '#F7FAFC' },
  mapTotal: { marginTop: spacing.xs, fontFamily: fonts.extrabold, fontSize: fontSizes.xl, color: colors.text },
  mapSubtitle: { marginTop: spacing.xs, fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.textMuted },
  updatedText: { maxWidth: 150, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, color: colors.textMuted, textAlign: 'right' },
  mapViewport: { height: 390, backgroundColor: colors.background },
  mapAction: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  mapActionText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.primary },
  inlineNote: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.danger, textAlign: 'center' },
  section: { gap: spacing.md, paddingTop: spacing.sm },
  decisionRow: { minHeight: 84, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.md },
  decisionDot: { width: 24, height: 24, borderRadius: 12 },
  decisionCopy: { flex: 1, gap: spacing.xs },
  decisionTitle: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
  decisionSubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.textMuted },
  todayRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.sm },
  calendarIcon: { width: 68, height: 68, borderRadius: 34, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F3F5F9' },
  todayCopy: { flex: 1, gap: spacing.sm },
  todayTitle: { fontFamily: fonts.semibold, fontSize: fontSizes.md, lineHeight: 22, color: colors.text },
  linkText: { fontFamily: fonts.medium, fontSize: fontSizes.md, color: colors.primary },
  rangeTabs: { minHeight: 52, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border },
  rangeTab: { minWidth: 88, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' },
  rangeTabActive: { borderBottomColor: colors.primary },
  rangeText: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.textMuted },
  rangeTextActive: { fontFamily: fonts.medium, color: colors.primary },
  sectionHint: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.textMuted },
  statusRow: { flexDirection: 'row', paddingVertical: spacing.md },
  statusMetric: { flex: 1, minWidth: 0, alignItems: 'center', gap: spacing.xs, paddingHorizontal: 2 },
  statusMetricBorder: { borderLeftWidth: 1, borderLeftColor: colors.border },
  statusDot: { width: 13, height: 13, borderRadius: 7 },
  statusCount: { fontFamily: fonts.medium, fontSize: 27, color: colors.text },
  statusLabel: { fontFamily: fonts.regular, fontSize: 11, color: colors.text, textAlign: 'center' },
  statusPercent: { fontFamily: fonts.regular, fontSize: 11, color: colors.textMuted },
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  flexCopy: { flex: 1 },
  barangayRow: { gap: spacing.sm, paddingVertical: spacing.sm },
  barangayHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm },
  barangayName: { flex: 1, fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
  barangayCount: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  barTrack: { height: 14, overflow: 'hidden', borderRadius: 7, backgroundColor: '#E9EDF3' },
  barFill: { height: '100%', flexDirection: 'row-reverse', overflow: 'hidden', borderRadius: 7, backgroundColor: '#69758A' },
  barUrgent: { height: '100%', backgroundColor: '#F87171' },
  disclosureRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border },
  disclosureText: { flex: 1, fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  readinessMetrics: { flexDirection: 'row', paddingVertical: spacing.lg },
  readinessMetric: { flex: 1, alignItems: 'center', gap: spacing.xs },
  readinessCount: { fontFamily: fonts.semibold, fontSize: fontSizes.xxl, color: colors.text },
  capacityCard: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#F2F6FC' },
  capacityValue: { fontFamily: fonts.extrabold, fontSize: 42, color: colors.text },
  capacityLabel: { fontFamily: fonts.medium, fontSize: fontSizes.lg, color: colors.text },
  capacityHint: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  capacityTrack: { height: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: '#C7CDD6' },
  capacityFill: { height: '100%', borderRadius: 3, backgroundColor: colors.text },
  centerRow: { minHeight: 116, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.md },
  centerAccent: { alignSelf: 'stretch', width: 4, borderRadius: 2, backgroundColor: colors.unverified },
  centerIcon: { width: 58, height: 58, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7ED' },
  centerName: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  centerMeta: { marginTop: spacing.xs, fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.45)' },
  scopeSheet: { maxHeight: '86%', gap: spacing.md, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white },
  sheetHandle: { alignSelf: 'center', width: 48, height: 5, borderRadius: 3, backgroundColor: '#C7CDD6' },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  sheetTitle: { marginTop: spacing.xs, fontFamily: fonts.bold, fontSize: fontSizes.xl, color: colors.text },
  sheetLabel: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  filterChip: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full },
  filterChipActive: { borderColor: colors.text, backgroundColor: colors.text },
  filterChipText: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.text },
  filterChipTextActive: { color: colors.white },
  barangayList: { maxHeight: 260, borderTopWidth: 1, borderTopColor: colors.border },
  sheetOption: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border },
  sheetOptionText: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.text },
  sheetOptionTextActive: { fontFamily: fonts.semibold, color: colors.primary },
  applyButton: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.primary },
  applyButtonText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.white },
});
