import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const mayorSituationsStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  horizontalContent: { paddingHorizontal: spacing.lg, backgroundColor: colors.background },
  flexCopy: { flex: 1 },
  sectionSwitch: { minHeight: 64, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border },
  sectionSwitchButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' },
  sectionSwitchButtonActive: { borderBottomColor: colors.primary },
  sectionSwitchText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.textMuted },
  sectionSwitchTextActive: { color: colors.primary },
  mapCard: { height: 390, marginHorizontal: spacing.md, marginTop: spacing.md, overflow: 'hidden', borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.background },
  mapViewport: { flex: 1 },
  mapSummary: { position: 'absolute', left: spacing.md, top: spacing.lg, width: 220, gap: spacing.sm, padding: spacing.md, borderRadius: radius.lg, backgroundColor: 'rgba(255,255,255,0.94)', shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 4 },
  eyebrow: { fontFamily: fonts.medium, fontSize: fontSizes.xs, letterSpacing: 0.5, color: '#46536A' },
  mapTotal: { fontFamily: fonts.extrabold, fontSize: fontSizes.xl, color: colors.text },
  mapSummaryText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, lineHeight: 20, color: colors.textMuted },
  openMapButton: { position: 'absolute', right: spacing.md, top: spacing.md, minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.full, backgroundColor: 'rgba(255,255,255,0.92)' },
  openMapText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.primary },
  mapError: { position: 'absolute', left: spacing.md, right: spacing.md, bottom: spacing.sm, padding: spacing.sm, borderRadius: radius.sm, backgroundColor: 'rgba(17,24,39,0.82)', fontFamily: fonts.medium, fontSize: fontSizes.xs, color: colors.white, textAlign: 'center' },
  stickyToolbar: { paddingHorizontal: spacing.md, paddingTop: spacing.md, backgroundColor: colors.background, borderBottomWidth: 1, borderBottomColor: colors.border },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  searchBox: { flex: 1, minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: '#BBC3CE', borderRadius: radius.lg, backgroundColor: colors.white },
  searchInput: { flex: 1, minHeight: 56, fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.text },
  filterButton: { width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#BBC3CE', borderRadius: radius.lg, backgroundColor: colors.white },
  filterBadge: { position: 'absolute', right: 5, top: 4, minWidth: 22, height: 22, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5, borderRadius: 11, backgroundColor: colors.primary },
  filterBadgeText: { fontFamily: fonts.bold, fontSize: fontSizes.xs, color: colors.white },
  filterSummaryRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  filterSummaryText: { flex: 1, fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  changeText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.primary },
  compactToolbarRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  compactTitle: { fontFamily: fonts.bold, fontSize: fontSizes.lg, color: colors.text },
  compactSubtitle: { marginTop: 3, fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.textMuted },
  compactIcon: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center' },
  resultsSheet: { marginTop: 0, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white },
  sheetHandle: { alignSelf: 'center', width: 54, height: 5, marginBottom: spacing.lg, borderRadius: 3, backgroundColor: '#C4CAD4' },
  resultsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  resultsTitle: { flex: 1, fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  newestLabel: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  newestText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  statusSummary: { minHeight: 50, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border },
  statusSummaryItem: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  statusDot: { width: 13, height: 13, borderRadius: 7 },
  statusSummaryText: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.textMuted },
  statusSeparator: { fontFamily: fonts.bold, fontSize: fontSizes.sm, color: colors.text },
  inlineWarning: { paddingVertical: spacing.sm, fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.danger },
  searchingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.sm },
  stateCard: { minHeight: 130, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border },
  stateTitle: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text, textAlign: 'center' },
  stateText: { fontFamily: fonts.regular, fontSize: fontSizes.xs, lineHeight: 18, color: colors.textMuted, textAlign: 'center' },
  retryButton: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.full, backgroundColor: colors.primary },
  retryText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.white },
  reportRow: { minHeight: 154, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.md, paddingLeft: spacing.sm },
  reportRowHighlighted: { borderLeftWidth: 3, borderLeftColor: colors.primary, paddingLeft: spacing.xs },
  thumbnail: { width: 112, height: 120, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: '#EDF1F5' },
  thumbnailLabel: { position: 'absolute', left: 5, right: 5, bottom: 7, fontFamily: fonts.medium, fontSize: 9, lineHeight: 12, color: colors.text, textAlign: 'center' },
  mapLineOne: { position: 'absolute', width: 150, height: 2, backgroundColor: '#D7DDE5', transform: [{ rotate: '-32deg' }] },
  mapLineTwo: { position: 'absolute', width: 150, height: 2, backgroundColor: '#D7DDE5', transform: [{ rotate: '48deg' }] },
  mapLineThree: { position: 'absolute', width: 95, height: 2, backgroundColor: '#D7DDE5', transform: [{ rotate: '8deg' }] },
  reportCopy: { flex: 1, gap: 6 },
  reportTitleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  reportTitle: { flex: 1, fontFamily: fonts.bold, fontSize: fontSizes.lg, color: colors.text },
  statusPill: { minHeight: 28, justifyContent: 'center', paddingHorizontal: spacing.sm, borderWidth: 1.5, borderRadius: radius.full },
  statusPillText: { fontFamily: fonts.semibold, fontSize: 9 },
  reportDescription: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  reportMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.textMuted },
  moreSection: { gap: spacing.sm, paddingVertical: spacing.lg },
  moreTitle: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  moreSubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  loadMoreButton: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  loadMoreText: { fontFamily: fonts.medium, fontSize: fontSizes.md, color: colors.primary },
  showingText: { paddingVertical: spacing.sm, fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted, textAlign: 'center' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(15,23,42,0.45)' },
  filterSheet: { maxHeight: '86%', gap: spacing.md, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white },
  filterSheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  filterSheetTitle: { marginTop: spacing.xs, fontFamily: fonts.bold, fontSize: fontSizes.xl, color: colors.text },
  filterLabel: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },
  choiceWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  choice: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full },
  choiceActive: { borderColor: colors.text, backgroundColor: colors.text },
  choiceText: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.text },
  choiceTextActive: { color: colors.white },
  barangayList: { maxHeight: 250, borderTopWidth: 1, borderTopColor: colors.border },
  barangayOption: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border },
  barangayOptionText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  barangayOptionTextActive: { fontFamily: fonts.semibold, color: colors.primary },
  filterActions: { flexDirection: 'row', gap: spacing.sm },
  resetButton: { minHeight: 48, minWidth: 90, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.full },
  resetText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },
  applyButton: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.primary },
  applyText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.white },
  priorityContent: { paddingHorizontal: spacing.lg, paddingTop: spacing.sm, gap: spacing.lg },
  readinessSummary: { gap: spacing.xs, padding: spacing.lg, borderRadius: radius.xl, backgroundColor: '#F3F7FD' },
  summaryValue: { fontFamily: fonts.extrabold, fontSize: 42, color: colors.text },
  summaryLabel: { fontFamily: fonts.semibold, fontSize: fontSizes.lg, color: colors.text },
  summaryMeta: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.textMuted },
  priorityCard: { minHeight: 110, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md, paddingRight: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.white },
  priorityAccent: { alignSelf: 'stretch', width: 5, backgroundColor: colors.unverified },
  priorityIcon: { width: 58, height: 58, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7ED' },
  priorityName: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  priorityMeta: { marginTop: spacing.xs, fontFamily: fonts.regular, fontSize: fontSizes.xs, color: colors.textMuted },
});
