import { StyleSheet } from 'react-native';

import { officialNavMetrics } from '../components/officialBottomNav.styles';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const mdrrmoSettingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: officialNavMetrics.barHeight + spacing.xl,
  },
  screenTitle: {
    marginBottom: spacing.md,
    fontFamily: fonts.semibold,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: colors.text,
  },
  identityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: '#D8E3FF',
  },
  avatarText: {
    fontFamily: fonts.bold,
    fontSize: 32,
    color: colors.primary,
  },
  identityCopy: {
    flex: 1,
    minWidth: 0,
  },
  identityName: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 27,
    color: colors.text,
  },
  identityRole: {
    marginTop: spacing.xs,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.textMuted,
  },
  viewProfileButton: {
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
    paddingVertical: spacing.xs,
  },
  viewProfileText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.md,
    color: colors.primary,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: -spacing.sm,
    backgroundColor: '#CBD5E1',
  },
  section: {
    paddingTop: spacing.sm,
    paddingBottom: 2,
  },
  sectionLabel: {
    marginBottom: 2,
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    letterSpacing: 0.35,
    color: '#53617A',
  },
  settingsRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: 6,
  },
  rowCopy: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    fontFamily: fonts.medium,
    fontSize: 16,
    color: colors.text,
  },
  rowSubtitle: {
    marginTop: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 16,
    color: '#62708A',
  },
  rowValue: {
    maxWidth: '30%',
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: '#62708A',
    textAlign: 'right',
  },
  logoutTitle: {
    fontFamily: fonts.medium,
    fontSize: 16,
    color: colors.unverified,
  },
  logoutRow: {
    minHeight: 52,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  footerVersion: {
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.textMuted,
    textAlign: 'center',
  },
  stateBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: radius.lg,
    backgroundColor: '#F8FAFC',
  },
  stateText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
  },
  retryText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.primary,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(17, 24, 39, 0.48)',
  },
  securityCard: {
    width: '100%',
    maxWidth: 460,
    maxHeight: '88%',
    alignSelf: 'center',
    padding: spacing.lg,
    gap: spacing.md,
    borderRadius: radius.xl,
    backgroundColor: colors.white,
  },
  securityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  securityTitle: {
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    color: colors.text,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityIntro: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 20,
    color: colors.textMuted,
  },
  securityNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.primaryLight,
  },
  securityNoticeText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.text,
  },
  inputGroup: {
    gap: spacing.sm,
  },
  inputLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  passwordInputRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingLeft: spacing.md,
    backgroundColor: colors.white,
  },
  passwordInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: spacing.sm,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  passwordEye: {
    width: 46,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passwordError: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.unverified,
  },
  securitySubmit: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    backgroundColor: colors.primary,
  },
  securitySubmitDisabled: {
    opacity: 0.55,
  },
  securitySubmitText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.white,
  },
});
