import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';
import { officialNavMetrics } from '../components/officialBottomNav.styles';

export const mdrrmoCommandStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: {
    paddingTop: spacing.md,
    paddingBottom: officialNavMetrics.barHeight + spacing.xxl,
    gap: spacing.xl,
  },
  padded: { paddingHorizontal: spacing.lg },
  stackedSections: { gap: spacing.md },
  section: { gap: spacing.sm, paddingHorizontal: spacing.lg },
  sectionDivider: { height: StyleSheet.hairlineWidth, backgroundColor: '#CBD5E1' },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sectionLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    letterSpacing: 0.45,
    color: '#46546D',
  },
  link: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm },
  linkText: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.primary },

  mapHero: { width: '100%', overflow: 'hidden', backgroundColor: '#07182A' },
  mapFill: { ...StyleSheet.absoluteFillObject },
  emptyMap: {
    opacity: 0.72,
    filter: 'blur(2px)',
    transform: [{ scale: 1.02 }],
  },
  mapScrim: { ...StyleSheet.absoluteFillObject },
  emptyMapContent: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    bottom: spacing.xxl,
    gap: spacing.md,
    maxWidth: '62%',
    zIndex: 2,
  },
  escalationTop: {
    position: 'absolute',
    top: spacing.xl,
    left: spacing.lg,
    right: spacing.lg,
    gap: spacing.md,
    maxWidth: '62%',
    zIndex: 2,
  },
  escalationCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: -12,
    marginBottom: 12,
  },
  alertDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#FF5B52' },
  escalationMeta: { gap: 2 },
  escalationCount: { fontFamily: fonts.medium, fontSize: fontSizes.md, lineHeight: 18, color: '#FF6B61' },
  escalationStatus: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    lineHeight: 20,
    color: '#FF6158',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  escalationBarangay: { color: colors.white },
  escalationDate: { fontFamily: fonts.regular, fontSize: fontSizes.md, lineHeight: 18, color: '#B6C1D0' },
  escalationTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 28,
    color: colors.white,
  },
  mediaThumb: {
    width: 86,
    height: 86,
    borderRadius: radius.md,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.86)',
    backgroundColor: '#1B2B3F',
  },
  mediaImage: { width: '100%', height: '100%' },
  mediaPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  mediaBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    borderRadius: radius.sm,
    paddingHorizontal: 7,
    paddingVertical: 4,
    backgroundColor: 'rgba(7,24,42,0.82)',
  },
  mediaBadgeText: { fontFamily: fonts.bold, fontSize: fontSizes.xs, color: colors.white },
  mediaCaption: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#B6C1D0' },
  heroBottom: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    bottom: spacing.lg,
    gap: spacing.md,
    zIndex: 2,
  },
  heroActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  incidentLink: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 44 },
  incidentLinkText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: '#4D91FF' },
  pager: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  pagerButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pagerText: { fontFamily: fonts.medium, fontSize: fontSizes.xs, color: colors.white },
  emptyHeroText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 22,
    color: '#B6C1D0',
  },

  pipelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 2,
  },
  pipelineStep: {
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: spacing.xs,
  },
  pipelineDot: { width: 9, height: 9, borderRadius: 5 },
  pipelineValue: { fontFamily: fonts.extrabold, fontSize: 30, lineHeight: 36 },
  pipelineLabel: { fontFamily: fonts.regular, fontSize: 11, color: '#526078', textAlign: 'center' },
  pipelineArrow: { width: 14, paddingTop: 9, alignItems: 'center' },

  directoryCard: {
    overflow: 'hidden',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    shadowColor: '#0F2044',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  directoryMap: { height: 250, backgroundColor: '#EDF2F5' },
  directoryMapOverlay: { ...StyleSheet.absoluteFillObject, padding: spacing.md },
  addCircle: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F2044',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  directoryCounts: { flexDirection: 'row', paddingVertical: 6 },
  directoryMetric: { flex: 1, alignItems: 'center', gap: 1, paddingVertical: 2, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  directoryMetricLast: { borderRightWidth: 0 },
  directoryCount: { fontFamily: fonts.extrabold, fontSize: 20, lineHeight: 24, color: colors.text },
  directoryMetricLabel: { fontFamily: fonts.regular, fontSize: 11, lineHeight: 14, color: colors.text },
  directoryFooter: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#CBD5E1', paddingVertical: 8, paddingHorizontal: spacing.md, alignItems: 'center' },
  directoryFooterText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#526078' },

  readinessCard: { borderRadius: radius.md, borderWidth: 1, borderColor: '#DCE8FA', backgroundColor: '#F3F7FD', padding: spacing.md, gap: spacing.md },
  readinessTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.md },
  capacityCopy: { flex: 1, minWidth: 0 },
  reviewBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingTop: 4 },
  reviewBadgeText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  capacityValue: { fontFamily: fonts.extrabold, fontSize: 34, lineHeight: 40, color: '#061B3D' },
  capacityLabel: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  readinessBar: { height: 4, borderRadius: 2, backgroundColor: '#061B3D' },
  readinessMetrics: { flexDirection: 'row' },
  readinessMetric: { flex: 1, alignItems: 'center', gap: 2, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  readinessMetricLast: { borderRightWidth: 0 },
  readinessMetricValue: { fontFamily: fonts.extrabold, fontSize: 22, color: colors.text },
  readinessMetricLabel: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: '#526078' },
  capacityMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: '#62708A' },
  reviewHeader: { marginTop: spacing.md },
  reviewLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    letterSpacing: 0.45,
    color: '#46546D',
  },
  reviewCard: { flexDirection: 'row', overflow: 'hidden', borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white },
  reviewAccent: { width: 4, backgroundColor: '#FF5B52' },
  reviewMap: { width: 88, minHeight: 96, backgroundColor: '#0A213A' },
  reviewCopy: { flex: 1, paddingVertical: spacing.sm, paddingHorizontal: spacing.sm + 2, gap: 6, justifyContent: 'center' },
  reviewIdentity: { gap: 2 },
  reviewNameRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  reviewName: { flex: 1, fontFamily: fonts.bold, fontSize: fontSizes.md, lineHeight: 18, color: colors.text },
  priorityPill: { borderRadius: radius.full, borderWidth: 1, borderColor: '#FF5B52', paddingHorizontal: spacing.sm, paddingVertical: 4 },
  priorityPillText: { fontFamily: fonts.medium, fontSize: fontSizes.xs, color: '#F04444' },
  reviewMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, lineHeight: 16, color: '#62708A' },
  reviewAction: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  reviewActionText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.primary },
  incompleteRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md },
  incompleteCopy: { flex: 1, fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },

  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(7, 24, 42, 0.48)' },
  sheet: { backgroundColor: colors.white, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, paddingBottom: spacing.xl },
  sheetHandle: { width: 44, height: 5, borderRadius: 3, backgroundColor: '#C5C9D0', alignSelf: 'center', marginBottom: spacing.lg },
  sheetOverline: { fontFamily: fonts.medium, fontSize: fontSizes.xs, letterSpacing: 0.6, color: colors.text, marginBottom: spacing.sm },
  sheetTitle: { fontFamily: fonts.bold, fontSize: fontSizes.xxl, color: colors.text },
  sheetSubtitle: { marginTop: spacing.sm, marginBottom: spacing.lg, fontFamily: fonts.regular, fontSize: fontSizes.sm, lineHeight: 20, color: '#526078' },
  pickerRow: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#CBD5E1' },
  pickerIcon: { width: 48, alignItems: 'center' },
  pickerCopy: { flex: 1, gap: 4 },
  pickerTitle: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  pickerSubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#62708A' },
  cancelButton: { minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md },
  cancelText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
});
