import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';
import { officialNavMetrics } from '../components/officialBottomNav.styles';

export const mdrrmoCommandStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: {
    paddingTop: spacing.md,
    paddingBottom: officialNavMetrics.barHeight + spacing.xxl,
    gap: 0,
  },
  commandStickyHeader: {
    zIndex: 10,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
  },
  commandScrollContent: { paddingTop: 0 },
  padded: { paddingHorizontal: spacing.lg, paddingBottom: spacing.md },
  section: { gap: spacing.sm, paddingHorizontal: spacing.lg },
  sectionDivider: { height: StyleSheet.hairlineWidth, backgroundColor: '#CBD5E1' },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sectionLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    letterSpacing: 0.45,
    color: '#46546D',
  },
  link: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm },
  linkText: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.navigationActive },

  commandHero: { width: '100%', backgroundColor: colors.white },
  mapHero: {
    width: '100%',
    height: 285,
    overflow: 'hidden',
    backgroundColor: '#E8F1F5',
  },
  mapFill: { ...StyleSheet.absoluteFill },
  mapEscalationBadge: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
    paddingHorizontal: 8,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  mapEscalationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  mapEscalationBadgeText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
  },
  mapPager: {
    position: 'absolute',
    bottom: spacing.md,
    right: spacing.lg,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    paddingHorizontal: 2,
    borderRadius: radius.full,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 4,
  },
  mapPagerButton: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapPagerText: {
    minWidth: 34,
    fontFamily: fonts.regular,
    fontSize: 10,
    color: '#526078',
    textAlign: 'center',
  },
  activeIncidentCard: {
    paddingHorizontal: spacing.lg,
    paddingTop: 12,
    paddingBottom: spacing.sm,
    gap: 10,
    backgroundColor: colors.white,
  },
  activeIncidentTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  activeIncidentCopy: { flex: 1, flexShrink: 1, minWidth: 0, gap: 0 },
  activeIncidentEyebrow: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.sm,
    lineHeight: 16,
    color: colors.escalated,
  },
  activeIncidentTitle: {
    fontFamily: fonts.bold,
    fontSize: 24,
    lineHeight: 27,
    color: colors.text,
  },
  activeIncidentMeta: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 18,
    color: '#6D7B92',
  },
  openIncidentAction: {
    width: 62,
    alignItems: 'center',
    gap: 3,
  },
  openIncidentCircle: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.navigationActive,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 7,
    elevation: 4,
  },
  openIncidentLabel: {
    fontFamily: fonts.semibold,
    fontSize: 9,
    color: colors.navigationActive,
    textAlign: 'center',
  },
  activeIncidentQuote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(183, 93, 50, 0.08)',
  },
  activeIncidentQuoteAccent: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 5,
    backgroundColor: colors.escalated,
  },
  activeIncidentQuoteMark: {
    width: 28,
    marginTop: -3,
    fontFamily: fonts.bold,
    fontSize: 34,
    lineHeight: 36,
    color: colors.escalated,
    textAlign: 'center',
  },
  activeIncidentQuoteCopy: { flex: 1, minWidth: 0, gap: spacing.xs },
  activeIncidentQuoteText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 21,
    color: colors.text,
  },
  activeIncidentQuoteSource: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: '#6D7B92',
  },
  incidentTimeline: {
    minHeight: 76,
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
  },
  incidentTimelineLine: {
    position: 'absolute',
    top: 12,
    // Keep the translucent connector outside the completed timeline circles.
    left: '20%',
    right: '20%',
    height: 2,
    backgroundColor: 'rgba(15, 32, 68, 0.14)',
  },
  incidentTimelineStep: {
    width: '31%',
    alignItems: 'center',
    gap: 2,
    zIndex: 1,
  },
  incidentTimelineDot: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: 'rgba(15, 32, 68, 0.14)',
  },
  incidentTimelineDotCurrent: {
    backgroundColor: colors.escalated,
    shadowColor: colors.escalated,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 7,
    elevation: 4,
  },
  incidentTimelineDotPending: { backgroundColor: '#CBD5E1' },
  incidentTimelineLabel: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: colors.text,
    textAlign: 'center',
  },
  incidentTimelineName: {
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 13,
    color: '#6D7B92',
    textAlign: 'center',
  },
  activeIncidentEmpty: {
    minHeight: 260,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    padding: spacing.xl,
    backgroundColor: colors.white,
  },
  activeIncidentEmptyIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: 'rgba(15, 32, 68, 0.08)',
  },
  activeIncidentEmptyTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.lg,
    color: colors.text,
  },
  activeIncidentEmptyBody: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: '#6D7B92',
    textAlign: 'center',
  },
  alertDot: { width: 9, height: 9, borderRadius: 5 },

  quickResponseSection: {
    gap: 6,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  quickResponseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 3,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  quickResponseTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    color: colors.text,
  },
  quickResponseActions: {
    minHeight: 58,
    flexDirection: 'row',
    paddingBottom: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  quickResponseAction: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingHorizontal: 2,
  },
  quickResponseActionBorder: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: '#D9E1EC',
  },
  quickResponseActionLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 15,
    color: colors.text,
    textAlign: 'center',
  },

  fieldUpdatesSection: {
    gap: 12,
    paddingHorizontal: spacing.lg,
    paddingTop: 12,
    paddingBottom: spacing.sm,
  },
  fieldUpdatesHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  fieldUpdatesHeadingCopy: { flex: 1, minWidth: 0, gap: 0 },
  fieldUpdatesTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 27,
    color: colors.text,
  },
  fieldUpdatesSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: '#62708A',
  },
  fieldUpdatesViewAll: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginTop: -6,
  },
  fieldUpdatesViewAllText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.navigationActive,
  },
  fieldUpdateCards: {
    gap: 12,
    paddingLeft: spacing.xs,
    paddingRight: spacing.lg,
    paddingVertical: spacing.xs,
  },
  fieldUpdateCard: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E1E8F2',
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 3,
  },
  fieldUpdateMediaFrame: {
    height: 190,
    overflow: 'hidden',
    backgroundColor: '#EAF0F7',
  },
  fieldUpdateMedia: { width: '100%', height: '100%' },
  fieldUpdateMediaPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  fieldUpdateMediaPlaceholderText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: '#62708A',
  },
  fieldUpdateMediaLabel: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    maxWidth: '78%',
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(7, 24, 42, 0.82)',
  },
  fieldUpdateMediaLabelText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xs,
    color: colors.white,
    textTransform: 'uppercase',
  },
  fieldUpdateMediaCount: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(7, 24, 42, 0.82)',
  },
  fieldUpdateMediaCountText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xs,
    color: colors.white,
  },
  fieldUpdateCardCopy: { gap: spacing.xs, padding: spacing.md },
  fieldUpdateCardTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    lineHeight: 23,
    color: colors.text,
  },
  fieldUpdateCardBody: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: '#526078',
  },
  fieldUpdateMapAction: {
    minHeight: 38,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: 'auto',
  },
  fieldUpdateCardAction: {
    minHeight: 28,
    gap: spacing.xs,
    marginTop: 0,
  },
  fieldUpdateMapActionText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.navigationActive,
  },
  fieldUpdatesEmptyCard: {
    minHeight: 372,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: '#E1E8F2',
    borderRadius: radius.sm,
    backgroundColor: colors.white,
  },
  fieldUpdatesEmptyIcon: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
    borderRadius: 27,
    backgroundColor: 'rgba(15, 32, 68, 0.08)',
  },
  fieldUpdatesEmptyTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.text,
    textAlign: 'center',
  },
  fieldUpdatesEmptyBody: {
    maxWidth: 270,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: '#6D7B92',
    textAlign: 'center',
  },
  earlierDivider: { height: StyleSheet.hairlineWidth, backgroundColor: '#D9E1EC' },
  earlierHeader: { gap: 2 },
  earlierTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 27,
    color: colors.text,
  },
  earlierSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: '#6D7B92',
  },
  earlierTimeline: { gap: 0 },
  earlierItem: { minHeight: 112, flexDirection: 'row', alignItems: 'stretch' },
  earlierTimelineRail: { width: 42, alignItems: 'center' },
  earlierTimelineRailSingle: { paddingTop: 20 },
  earlierTimelineLine: {
    position: 'absolute',
    top: 34,
    bottom: -10,
    width: 2,
    backgroundColor: '#DFE7F1',
  },
  earlierStatusIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
  },
  earlierItemBody: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingBottom: spacing.md,
    marginLeft: spacing.sm,
  },
  earlierItemBorder: {
    marginBottom: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#D9E1EC',
  },
  earlierItemCopy: { flex: 1, minWidth: 0, gap: 3 },
  earlierItemTime: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: '#6D7B92',
  },
  earlierItemBarangay: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  earlierItemTitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    color: '#526078',
  },
  earlierItemMedia: {
    width: 76,
    height: 68,
    borderRadius: radius.sm,
    backgroundColor: '#EAF0F7',
  },
  earlierItemMediaPlaceholder: {
    width: 76,
    height: 68,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
    backgroundColor: '#EEF3F8',
  },
  earlierLoading: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  earlierEmpty: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  earlierEmptyText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: '#6D7B92',
  },

  directoryCard: {
    overflow: 'hidden',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    shadowColor: '#0F2044',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  directoryMap: { height: 250, backgroundColor: '#EDF2F5' },
  directoryMapOverlay: { ...StyleSheet.absoluteFill, padding: spacing.md },
  addCircle: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F2044',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  directoryCounts: { flexDirection: 'row', paddingVertical: 6 },
  directoryMetric: { flex: 1, alignItems: 'center', gap: 1, paddingVertical: 2, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  directoryMetricLast: { borderRightWidth: 0 },
  directoryCount: { fontFamily: fonts.extrabold, fontSize: 20, lineHeight: 24, color: colors.text },
  directoryMetricLabel: { fontFamily: fonts.regular, fontSize: 11, lineHeight: 14, color: colors.text },
  directoryFooter: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#CBD5E1', paddingVertical: 8, paddingHorizontal: spacing.md, alignItems: 'center' },
  directoryFooterText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#526078' },

  readinessCard: { borderRadius: radius.md, borderWidth: 1, borderColor: '#DCE8FA', backgroundColor: '#F3F7FD', padding: spacing.md, gap: spacing.md },
  readinessTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.md },
  capacityCopy: { flex: 1, minWidth: 0 },
  reviewBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingTop: 4 },
  reviewBadgeText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  capacityValue: { fontFamily: fonts.extrabold, fontSize: 34, lineHeight: 40, color: '#061B3D' },
  capacityLabel: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  readinessBar: { height: 4, borderRadius: 2, backgroundColor: '#061B3D' },
  readinessMetrics: { flexDirection: 'row' },
  readinessMetric: { flex: 1, alignItems: 'center', gap: 2, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  readinessMetricLast: { borderRightWidth: 0 },
  readinessMetricValue: { fontFamily: fonts.extrabold, fontSize: 22, color: colors.text },
  readinessMetricLabel: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: '#526078' },
  capacityMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, color: '#62708A' },
  reviewHeader: { marginTop: spacing.md },
  reviewLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    letterSpacing: 0.45,
    color: '#46546D',
  },
  reviewCard: { flexDirection: 'row', overflow: 'hidden', borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white },
  reviewAccent: { width: 4, backgroundColor: '#FF5B52' },
  reviewMap: { width: 88, minHeight: 96, backgroundColor: '#0A213A' },
  reviewCopy: { flex: 1, paddingVertical: spacing.sm, paddingHorizontal: spacing.sm + 2, gap: 6, justifyContent: 'center' },
  reviewIdentity: { gap: 2 },
  reviewNameRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  reviewName: { flex: 1, fontFamily: fonts.bold, fontSize: fontSizes.md, lineHeight: 18, color: colors.text },
  priorityPill: { borderRadius: radius.full, borderWidth: 1, borderColor: '#FF5B52', paddingHorizontal: spacing.sm, paddingVertical: 4 },
  priorityPillText: { fontFamily: fonts.medium, fontSize: fontSizes.xs, color: '#F04444' },
  reviewMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, lineHeight: 16, color: '#62708A' },
  reviewAction: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  reviewActionText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.navigationActive },
  incompleteRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md },
  incompleteCopy: { flex: 1, fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },

  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(7, 24, 42, 0.48)' },
  sheet: { backgroundColor: colors.white, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.xl },
  sheetOverline: { fontFamily: fonts.medium, fontSize: fontSizes.xs, letterSpacing: 0.6, color: colors.text, marginBottom: spacing.xs },
  sheetTitle: { fontFamily: fonts.bold, fontSize: fontSizes.xxl, color: colors.text },
  sheetSubtitle: { marginTop: spacing.xs, marginBottom: spacing.md, fontFamily: fonts.regular, fontSize: fontSizes.sm, lineHeight: 20, color: '#526078' },
  pickerRow: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#CBD5E1' },
  pickerIcon: { width: 48, alignItems: 'center' },
  pickerCopy: { flex: 1, gap: 4 },
  pickerTitle: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  pickerSubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#62708A' },
  cancelButton: { minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md },
  cancelText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
});
