import { StyleSheet } from 'react-native';

import { officialNavMetrics } from '../components/officialBottomNav.styles';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const mdrrmoSettingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scrollContent: {
    paddingTop: spacing.md,
    paddingBottom: officialNavMetrics.barHeight + spacing.xxl,
  },
  horizontalContent: {
    paddingHorizontal: spacing.lg,
  },
  hero: {
    minHeight: 150,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    overflow: 'hidden',
    backgroundColor: '#07162E',
  },
  contourOne: {
    position: 'absolute',
    width: 240,
    height: 130,
    right: -50,
    top: -30,
    borderWidth: 1,
    borderColor: 'rgba(170, 192, 220, 0.13)',
    borderRadius: radius.full,
    transform: [{ rotate: '-12deg' }],
  },
  contourTwo: {
    position: 'absolute',
    width: 210,
    height: 100,
    left: 90,
    bottom: -35,
    borderWidth: 1,
    borderColor: 'rgba(170, 192, 220, 0.12)',
    borderRadius: radius.full,
    transform: [{ rotate: '8deg' }],
  },
  heroAvatar: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#D8E3FF',
  },
  heroAvatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xxl,
    color: colors.primary,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  heroName: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 28,
    color: colors.white,
  },
  heroRole: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 21,
    color: '#B8C5D8',
  },
  heroAction: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  heroActionText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: '#70A4FF',
  },
  section: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
  },
  sectionLabel: {
    marginBottom: spacing.md,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    letterSpacing: 0.4,
    color: '#53617A',
  },
  row: {
    minHeight: 94,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#CBD5E1',
    paddingVertical: spacing.md,
  },
  rowIcon: {
    width: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowCopy: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    fontFamily: fonts.semibold,
    fontSize: 17,
    color: colors.text,
  },
  rowSubtitle: {
    marginTop: 6,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 21,
    color: '#62708A',
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: radius.full,
  },
  staticToggle: {
    width: 54,
    height: 30,
    padding: 3,
    alignItems: 'flex-end',
    justifyContent: 'center',
    borderRadius: radius.full,
  },
  staticToggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.white,
  },
  logoutTitle: {
    fontFamily: fonts.semibold,
    fontSize: 17,
    color: '#F0524A',
  },
  footerVersion: {
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.textMuted,
    textAlign: 'center',
  },
  stateBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: radius.lg,
    backgroundColor: '#F8FAFC',
  },
  stateText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
  },
  retryText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.primary,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(17, 24, 39, 0.48)',
  },
  securityCard: {
    width: '100%',
    maxWidth: 460,
    maxHeight: '88%',
    alignSelf: 'center',
    padding: spacing.lg,
    gap: spacing.md,
    borderRadius: radius.xl,
    backgroundColor: colors.white,
  },
  securityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  securityTitle: {
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    color: colors.text,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityIntro: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 20,
    color: colors.textMuted,
  },
  securityNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.primaryLight,
  },
  securityNoticeText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.text,
  },
  inputGroup: {
    gap: spacing.sm,
  },
  inputLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  passwordInputRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingLeft: spacing.md,
    backgroundColor: colors.white,
  },
  passwordInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: spacing.sm,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  passwordEye: {
    width: 46,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passwordError: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: colors.unverified,
  },
  securitySubmit: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    backgroundColor: colors.primary,
  },
  securitySubmitDisabled: {
    opacity: 0.55,
  },
  securitySubmitText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md,
    color: colors.white,
  },
});
