import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';
import { officialNavMetrics } from '../components/officialBottomNav.styles';

export const mdrrmoCommandStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  content: {
    paddingTop: spacing.md,
    paddingBottom: officialNavMetrics.barHeight + spacing.xxl,
    gap: spacing.xl,
  },
  padded: { paddingHorizontal: spacing.lg },
  section: { gap: spacing.md, paddingHorizontal: spacing.lg },
  sectionDivider: { height: StyleSheet.hairlineWidth, backgroundColor: '#CBD5E1' },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sectionLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    letterSpacing: 0.45,
    color: '#46546D',
  },
  link: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm },
  linkText: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.primary },

  mapHero: { width: '100%', overflow: 'hidden', backgroundColor: '#07182A' },
  mapFill: { ...StyleSheet.absoluteFillObject },
  mapScrim: { ...StyleSheet.absoluteFillObject },
  mapContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
    justifyContent: 'space-between',
  },
  escalationTop: { gap: spacing.md, maxWidth: '62%' },
  escalationCountRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  alertDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#FF5B52' },
  escalationCount: { fontFamily: fonts.medium, fontSize: fontSizes.md, color: '#FF6B61' },
  escalationStatus: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    color: '#FF6158',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  escalationBarangay: { color: colors.white },
  escalationDate: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: '#B6C1D0' },
  escalationTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    lineHeight: 28,
    color: colors.white,
  },
  mediaThumb: {
    width: 86,
    height: 86,
    borderRadius: radius.md,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.86)',
    backgroundColor: '#1B2B3F',
  },
  mediaImage: { width: '100%', height: '100%' },
  mediaPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  mediaBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    borderRadius: radius.sm,
    paddingHorizontal: 7,
    paddingVertical: 4,
    backgroundColor: 'rgba(7,24,42,0.82)',
  },
  mediaBadgeText: { fontFamily: fonts.bold, fontSize: fontSizes.xs, color: colors.white },
  mediaCaption: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#B6C1D0' },
  heroBottom: { gap: spacing.md },
  heroActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  incidentLink: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 44 },
  incidentLinkText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: '#4D91FF' },
  pager: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  pagerButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pagerText: { fontFamily: fonts.medium, fontSize: fontSizes.xs, color: colors.white },
  emptyHero: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.xl },
  emptyHeroTitle: { fontFamily: fonts.bold, fontSize: fontSizes.lg, color: colors.white },
  emptyHeroText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#B6C1D0', textAlign: 'center' },

  pipelineRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  pipelineStep: { flex: 1, minWidth: 0, alignItems: 'center', gap: 5 },
  pipelineDot: { width: 9, height: 9, borderRadius: 5 },
  pipelineValue: { fontFamily: fonts.extrabold, fontSize: 30, lineHeight: 36 },
  pipelineLabel: { fontFamily: fonts.regular, fontSize: 11, color: '#526078', textAlign: 'center' },
  pipelineArrow: { width: 24, paddingTop: 29, alignItems: 'center' },

  directoryCard: {
    overflow: 'hidden',
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    shadowColor: '#0F2044',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  directoryMap: { height: 250, backgroundColor: '#EDF2F5' },
  directoryMapOverlay: { ...StyleSheet.absoluteFillObject, padding: spacing.md, justifyContent: 'space-between' },
  directoryHeadline: { maxWidth: '80%', gap: 4 },
  directoryTitle: { fontFamily: fonts.bold, fontSize: fontSizes.lg, color: colors.text },
  directorySubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#526078' },
  addCircle: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F2044',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  directoryCounts: { flexDirection: 'row', paddingVertical: spacing.md },
  directoryMetric: { flex: 1, alignItems: 'center', gap: 3, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  directoryMetricLast: { borderRightWidth: 0 },
  directoryCount: { fontFamily: fonts.extrabold, fontSize: 27, color: colors.text },
  directoryMetricLabel: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  directoryFooter: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#CBD5E1', padding: spacing.md, alignItems: 'center' },
  directoryFooterText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#526078' },

  readinessCard: { borderRadius: radius.xl, borderWidth: 1, borderColor: '#DCE8FA', backgroundColor: '#F3F7FD', padding: spacing.lg, gap: spacing.lg },
  readinessTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  readinessLabel: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: colors.text },
  reviewBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  reviewBadgeText: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: colors.text },
  capacityValue: { fontFamily: fonts.extrabold, fontSize: 44, lineHeight: 50, color: '#061B3D' },
  capacityLabel: { fontFamily: fonts.regular, fontSize: fontSizes.md, color: colors.text },
  readinessBar: { height: 5, borderRadius: 3, backgroundColor: '#061B3D' },
  readinessMetrics: { flexDirection: 'row' },
  readinessMetric: { flex: 1, alignItems: 'center', gap: 4, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#CBD5E1' },
  readinessMetricLast: { borderRightWidth: 0 },
  readinessMetricValue: { fontFamily: fonts.extrabold, fontSize: 28, color: colors.text },
  readinessMetricLabel: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#526078' },
  capacityMeta: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#62708A' },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  reviewCount: { fontFamily: fonts.medium, fontSize: fontSizes.sm, color: '#F04444' },
  reviewCard: { flexDirection: 'row', overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white },
  reviewAccent: { width: 4, backgroundColor: '#FF5B52' },
  reviewMap: { width: 112, minHeight: 126, backgroundColor: '#0A213A' },
  reviewCopy: { flex: 1, padding: spacing.md, gap: spacing.sm },
  reviewNameRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  reviewName: { flex: 1, fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  priorityPill: { borderRadius: radius.full, borderWidth: 1, borderColor: '#FF5B52', paddingHorizontal: spacing.sm, paddingVertical: 4 },
  priorityPillText: { fontFamily: fonts.medium, fontSize: fontSizes.xs, color: '#F04444' },
  reviewMeta: { fontFamily: fonts.regular, fontSize: fontSizes.xs, lineHeight: 18, color: '#62708A' },
  reviewAction: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingTop: spacing.xs },
  reviewActionText: { fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.primary },
  incompleteRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.md },
  incompleteCopy: { flex: 1, fontFamily: fonts.semibold, fontSize: fontSizes.sm, color: colors.text },

  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(7, 24, 42, 0.48)' },
  sheet: { backgroundColor: colors.white, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, paddingBottom: spacing.xl },
  sheetHandle: { width: 44, height: 5, borderRadius: 3, backgroundColor: '#C5C9D0', alignSelf: 'center', marginBottom: spacing.lg },
  sheetOverline: { fontFamily: fonts.medium, fontSize: fontSizes.xs, letterSpacing: 0.6, color: colors.text, marginBottom: spacing.sm },
  sheetTitle: { fontFamily: fonts.bold, fontSize: fontSizes.xxl, color: colors.text },
  sheetSubtitle: { marginTop: spacing.sm, marginBottom: spacing.lg, fontFamily: fonts.regular, fontSize: fontSizes.sm, lineHeight: 20, color: '#526078' },
  pickerRow: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#CBD5E1' },
  pickerIcon: { width: 48, alignItems: 'center' },
  pickerCopy: { flex: 1, gap: 4 },
  pickerTitle: { fontFamily: fonts.bold, fontSize: fontSizes.md, color: colors.text },
  pickerSubtitle: { fontFamily: fonts.regular, fontSize: fontSizes.sm, color: '#62708A' },
  cancelButton: { minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md },
  cancelText: { fontFamily: fonts.semibold, fontSize: fontSizes.md, color: colors.text },
});
