import { Platform, StyleSheet } from 'react-native';
import { colors as themeColors, fonts, fontSizes, fontWeights, radius, spacing } from '../theme';
import { scaleByWidth } from '../../lib/layout';

export const registerColors = {
  background: themeColors.background,
  stepNode: '#e8f2ff',
  stepTimelineActive: '#042C5C',
  accent: '#000000',
  white: '#ffffff',
  gray: '#8A94A6',
  grayLight: '#D1D9E6',
  grayMuted: '#BCC5D3',
  text: themeColors.text,
  textLight: '#5A6A85',
  error: '#EF4444',
  inputBg: '#ffffff',
  inputBorder: '#D1D9E6',
  primary: themeColors.primary,
};

export const registerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: registerColors.background,
  },

  centeredBlock: {
    width: '100%',
  },

  fixedScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: spacing.md,
  },

  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.lg,
  },

  backButton: {
    position: 'absolute',
    top: spacing.sm,
    left: spacing.md,
    zIndex: 10,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(15,32,68,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    display: 'none',
    color: registerColors.white,
    fontSize: 18,
    lineHeight: 20,
    marginTop: -1,
  },

  settingsHeader: {
    minHeight: 64,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsHeaderButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsResetScrollContent: {
    flexGrow: 1,
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
  },

  screenTitle: {
    fontFamily: fonts.extrabold,
    fontSize: scaleByWidth(28),
    fontWeight: '800',
    textAlign: 'center',
    color: registerColors.text,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    letterSpacing: -1,
  },

  imageContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  imagePlaceholder: {
    width: '100%',
    height: '100%',
  },

  stepperWrapper: {
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: registerColors.white,
    alignItems: 'center',
  },
  singleStepTimelineRow: {
    width: '100%',
    height: 44,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  singleStepIncomingArea: {
    flex: 1,
    minWidth: 0,
    height: 22,
    justifyContent: 'center',
    overflow: 'visible',
  },
  singleStepNodeSlot: {
    width: 42,
    height: 44,
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 1,
  },
  singleStepOutgoingArea: {
    width: 52,
    height: 22,
    justifyContent: 'center',
    overflow: 'visible',
  },
  singleStepLineTrack: {
    width: '100%',
    height: 2,
    position: 'relative',
    overflow: 'visible',
    justifyContent: 'center',
  },
  singleStepLine: {
    width: '100%',
    height: 2,
    borderRadius: 1,
    backgroundColor: registerColors.stepTimelineActive,
    transformOrigin: 'left',
  },
  singleStepLineReverse: {
    transformOrigin: 'right',
  },
  singleStepMovingPercentage: {
    position: 'absolute',
    top: -25,
    width: 60,
    fontFamily: fonts.bold,
    fontSize: 17,
    lineHeight: 20,
    textAlign: 'center',
    color: registerColors.stepTimelineActive,
    backgroundColor: registerColors.white,
  },
  singleStepPhonePercentage: {
    position: 'absolute',
    top: -15,
    left: 4,
    width: 60,
    zIndex: 2,
    fontFamily: fonts.bold,
    fontSize: 17,
    lineHeight: 20,
    textAlign: 'left',
    color: registerColors.stepTimelineActive,
    backgroundColor: registerColors.white,
  },
  singleStepNodeContent: {
    width: 42,
    height: 44,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  stepCurrentNodeWrap: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCurrentPulseRing: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: registerColors.stepTimelineActive,
    opacity: 0.48,
  },
  stepCurrentNode: {
    width: 14,
    height: 14,
    borderRadius: radius.full,
    borderWidth: 2,
    borderColor: registerColors.stepTimelineActive,
    backgroundColor: registerColors.white,
  },
  singleStepLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: spacing.xs,
  },
  singleStepLabel: {
    width: 42,
    fontFamily: fonts.bold,
    fontSize: 11,
    textAlign: 'center',
    color: registerColors.stepTimelineActive,
    fontWeight: '700',
  },

  card: {
    backgroundColor: registerColors.white,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },

  stepContent: {
    width: '100%',
    alignItems: 'stretch',
  },

  stepTitle: {
    fontFamily: fonts.extrabold,
    fontSize: scaleByWidth(24),
    fontWeight: '800',
    textAlign: 'left',
    color: registerColors.text,
    letterSpacing: -0.5,
    marginBottom: spacing.xs,
  },
  centeredStepTitle: {
    textAlign: 'center',
  },
  registrationPhoneSectionLabel: {
    color: themeColors.textMuted,
    fontFamily: fonts.medium,
    fontSize: fontSizes.md,
    marginBottom: spacing.xs,
    textAlign: 'left',
  },
  registrationPhoneSubtitle: {
    color: registerColors.text,
    letterSpacing: 0,
    textAlign: 'left',
  },
  registrationPhoneSubtitleBold: {
    color: registerColors.text,
  },
  registrationPhoneContinueText: {
    color: registerColors.text,
  },
  stepSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: registerColors.text,
    lineHeight: 20,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  stepSubtitleBold: {
    fontFamily: fonts.extrabold,
    fontWeight: '900',
    color: registerColors.text,
  },
  settingsResetIntro: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    marginBottom: spacing.xl,
  },
  settingsResetFieldWrap: {
    marginBottom: 0,
  },
  settingsResetTitle: {
    fontFamily: fonts.extrabold,
    fontSize: scaleByWidth(34),
    letterSpacing: -1,
    color: themeColors.text,
    textAlign: 'left',
  },
  settingsResetSubtitle: {
    marginTop: spacing.sm,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 21,
    color: themeColors.textMuted,
    textAlign: 'left',
  },

  fieldLabel: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: registerColors.textLight,
    letterSpacing: 0.5,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },

  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    minHeight: 58,
    backgroundColor: registerColors.white,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  phoneRowFocused: {
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: registerColors.primary,
  },
  settingsResetPhoneRow: {
    minHeight: 52,
    paddingVertical: spacing.xs,
    borderWidth: 1,
    borderColor: registerColors.inputBorder,
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  settingsResetPhoneRowFocused: {
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 1.5,
    borderColor: themeColors.text,
  },
  phonePrefixBox: {
    paddingRight: spacing.sm,
    borderRightWidth: 1,
    borderRightColor: registerColors.grayLight,
    marginRight: spacing.sm,
  },
  phonePrefixText: {
    fontFamily: fonts.semibold,
    color: registerColors.text,
    fontSize: scaleByWidth(20),
    fontWeight: '600',
  },
  phoneInput: {
    fontFamily: fonts.regular,
    flex: 1,
    minWidth: 0,
    color: registerColors.text,
    fontSize: scaleByWidth(20),
    paddingVertical: 0,
    backgroundColor: 'transparent',
  },
  phoneHint: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: registerColors.gray,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  phoneHintLarge: {
    fontSize: fontSizes.lg,
    marginTop: spacing.sm,
    lineHeight: 22,
  },
  continueVerificationButton: {
    paddingVertical: spacing.sm,
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  continueVerificationText: {
    fontFamily: fonts.semibold,
    color: registerColors.primary,
    fontSize: fontSizes.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  settingsResetContinueVerificationText: {
    color: themeColors.text,
  },

  otpTargetText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: registerColors.textLight,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  otpTargetNumber: {
    fontFamily: fonts.bold,
    fontWeight: '700',
    color: registerColors.text,
  },
  otpBoxRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    marginBottom: spacing.lg,
  },
  otpBox: {
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: registerColors.inputBorder,
    backgroundColor: registerColors.inputBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpBoxFilled: {
    borderColor: registerColors.stepNode,
    backgroundColor: registerColors.white,
  },
  otpBoxActive: {
    borderColor: registerColors.primary,
    borderWidth: 2,
  },
  otpBoxError: {
    borderColor: registerColors.error,
    borderWidth: 2,
  },
  otpBoxText: {
    fontFamily: fonts.extrabold,
    fontWeight: '800',
    color: registerColors.text,
  },

  resendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: spacing.lg,
    gap: 4,
  },
  resendLabel: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: registerColors.textLight,
  },
  resendButton: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: registerColors.accent,
  },
  resendButtonDisabled: {
    color: registerColors.grayMuted,
  },
  resendTimer: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    fontWeight: '600',
    color: registerColors.gray,
  },

  primaryButton: {
    paddingVertical: spacing.sm + 4,
    paddingHorizontal: spacing.md,
    backgroundColor: '#042C5C',
    marginTop: spacing.xs,
    width: '100%',
    borderRadius: radius.md,
    alignItems: 'center',
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 5,
  },
  settingsResetPrimaryButton: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    paddingVertical: spacing.md,
    marginTop: spacing.sm + spacing.xs,
    borderRadius: radius.md,
    backgroundColor: themeColors.navigationActive,
  },
  primaryButtonDisabled: {
    backgroundColor: registerColors.grayLight,
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryButtonText: {
    fontFamily: fonts.semibold,
    color: registerColors.white,
    fontSize: fontSizes.xl,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  primaryButtonTextDisabled: {
    color: registerColors.gray,
  },

  fieldGroup: {
    marginBottom: spacing.md,
  },
  label: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: registerColors.text,
    marginBottom: 2,
    marginLeft: spacing.sm,
  },
  required: {
    color: registerColors.error,
  },
  input: {
    fontFamily: fonts.regular,
    backgroundColor: '#F5F6F8',
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    fontSize: fontSizes.lg,
    color: registerColors.text,
    minHeight: 52,
  },
  inputFocused: {
    borderWidth: 1.5,
    borderColor: '#acacac',
    backgroundColor: registerColors.white,
  },
  inputError: {
    borderWidth: 1.5,
    borderColor: registerColors.error,
  },
  dropdownInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectFieldText: {
    fontFamily: fonts.regular,
    flex: 1,
    marginLeft: 8,
    color: registerColors.text,
  },
  selectFieldPlaceholder: {
    color: '#aaa',
  },
  disabledInput: {
    backgroundColor: '#EAEAEA',
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  flex1: {
    flex: 1,
  },
  errorText: {
    fontFamily: fonts.medium,
    color: registerColors.error,
    fontSize: fontSizes.md,
    marginBottom: spacing.sm,
    textAlign: 'center',
    fontWeight: '500',
  },
  fieldErrorRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
    alignSelf: 'stretch',
  },
  fieldErrorText: {
    fontFamily: fonts.regular,
    flex: 1,
    color: registerColors.error,
    fontSize: fontSizes.sm,
    lineHeight: 18,
    textAlign: 'left',
  },
  fieldErrorRowCentered: {
    justifyContent: 'center',
  },
  fieldErrorTextCentered: {
    flex: 0,
    textAlign: 'center',
  },
  inputWithIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F6F8',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    minHeight: 52,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  inputWithIconRowFocused: {
    borderColor: '#acacac',
    backgroundColor: registerColors.white,
  },
  inputWithIconRowError: {
    borderColor: registerColors.error,
    backgroundColor: registerColors.white,
  },
  fieldLeadingIconBox: {
    minWidth: 44,
    paddingRight: spacing.sm,
    borderRightWidth: 1,
    borderRightColor: registerColors.grayLight,
    marginRight: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Matches inputWithIconField so icon rows and "+63" rows stay consistent.
  fieldLeadingPrefixText: {
    fontSize: fontSizes.lg,
    fontFamily: fonts.semibold,
    color: registerColors.text,
    lineHeight: fontSizes.lg + 2,
  },
  inputWithIconField: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSizes.lg,
    fontFamily: fonts.regular,
    color: registerColors.text,
    paddingVertical: 0,
    lineHeight: fontSizes.lg + 2,
  },
  checkboxError: {
    borderWidth: 1.5,
    borderColor: registerColors.error,
  },

  modernCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  circularCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CCC',
    marginRight: spacing.sm,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: registerColors.white,
  },
  circularCheckboxActive: {
    backgroundColor: registerColors.primary,
    borderColor: registerColors.primary,
  },
  checkboxText: {
    fontFamily: fonts.regular,
    flex: 1,
    fontSize: fontSizes.sm,
    color: registerColors.textLight,
  },
  linkText: {
    fontFamily: fonts.semibold,
    color: registerColors.primary,
    fontWeight: '600',
  },

  modernButton: {
    backgroundColor: '#042C5C',
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 4,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    marginTop: spacing.xs,
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  modernButtonText: {
    fontFamily: fonts.semibold,
    color: registerColors.white,
    fontSize: fontSizes.xl,
    fontWeight: '600',
    letterSpacing: 0.2,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: registerColors.white,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    maxHeight: '60%',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
    paddingTop: spacing.sm,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: registerColors.grayLight,
    borderRadius: 999,
    alignSelf: 'center',
    marginBottom: spacing.md,
  },
  modalTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    fontWeight: 'bold',
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  modalDivider: {
    height: 1,
    backgroundColor: '#f0f0f0',
  },
  modalOption: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  modalOptionSelected: {
    backgroundColor: registerColors.stepNode,
    borderRadius: radius.md,
  },
  modalOptionText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.lg,
    color: registerColors.text,
    textAlign: 'center',
  },
  modalOptionTextSelected: {
    fontFamily: fonts.bold,
    color: registerColors.primary,
    fontWeight: '700',
  },
  modalCloseButton: {
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: '#f5f5f5',
    borderRadius: radius.sm,
  },
  modalCloseText: {
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: fontSizes.lg,
    fontWeight: 'bold',
    color: registerColors.error,
  },

  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F6F8',
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 52,
    justifyContent: 'space-between',
  },
  dropdownText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.lg,
    color: registerColors.text,
    flex: 1,
  },
  dropdownPlaceholder: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.lg,
    color: '#aaa',
    flex: 1,
  },
  dropdownIcon: {
    fontSize: fontSizes.lg,
    color: '#aaa',
  },

  pinHintRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 6,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  pinHintText: {
    fontFamily: fonts.regular,
    flexShrink: 1,
    fontSize: fontSizes.sm,
    color: registerColors.gray,
    lineHeight: 18,
    textAlign: 'center',
  },
  pinInputWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'stretch',
    position: 'relative',
  },
  pinDisplayText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.lg,
    color: registerColors.text,
    paddingVertical: 0,
    letterSpacing: 6,
    lineHeight: fontSizes.lg + 6,
    textAlign: 'left',
  },
  pinHiddenInput: {
    ...StyleSheet.absoluteFill,
    color: 'transparent',
    fontSize: 1,
    letterSpacing: 0,
    padding: 0,
    margin: 0,
  },

  loginFieldWrap: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    marginBottom: spacing.md,
  },
  // Matches the resident login PIN input without its labels, icons, or shadow.
  registrationPinFieldWrap: {
    width: '100%',
    marginBottom: spacing.sm,
  },
  registrationPinFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    minHeight: 50,
    backgroundColor: registerColors.white,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  registrationPinFieldRowFocused: {
    borderColor: registerColors.primary,
    borderWidth: 1.5,
  },
  registrationPinFieldRowError: {
    borderColor: registerColors.error,
    borderWidth: 1.5,
  },
  registrationPhoneFieldWrap: {
    maxWidth: '100%',
  },
  registrationPhoneRow: {
    maxWidth: '100%',
    minHeight: 50,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: registerColors.inputBorder,
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  registrationPhonePrefixText: {
    fontSize: fontSizes.lg,
  },
  registrationPhoneInput: {
    fontSize: fontSizes.lg,
  },
  registrationPhoneRowFocused: {
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  loginFieldLabel: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: registerColors.textLight,
    letterSpacing: 0.5,
    marginBottom: spacing.sm,
    textAlign: 'left',
    alignSelf: 'stretch',
  },
  centeredFieldLabel: {
    textAlign: 'center',
  },
  phoneSwapIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  phoneSwapIconBtnPressed: {
    backgroundColor: '#EEF2FF',
    borderWidth: 1.5,
    borderColor: registerColors.primary,
  },
  phoneDisplayText: {
    fontFamily: fonts.regular,
    color: registerColors.text,
    fontSize: scaleByWidth(20),
    lineHeight: scaleByWidth(24),
    paddingVertical: 0,
    includeFontPadding: false,
  },
  phoneDisplayPlaceholder: {
    color: registerColors.grayMuted,
  },
  phoneLockedValue: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  pinIconBox: {
    paddingRight: spacing.sm,
    borderRightWidth: 1,
    borderRightColor: registerColors.grayLight,
    marginRight: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPinRow: {
    flex: 1,
    minWidth: 0,
  },
  forgotPasswordRow: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  forgotPasswordText: {
    fontSize: fontSizes.sm,
    color: registerColors.gray,
    textAlign: 'left',
  },
  forgotPasswordLink: {
    fontWeight: '800',
    color: registerColors.primary,
  },
  socialFollowSection: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    marginTop: spacing.xs,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: registerColors.grayLight,
    gap: spacing.xs,
  },
  loginSignUpButton: {
    paddingVertical: spacing.md,
    width: '100%',
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    marginBottom: 0,
  },
  loginSignUpButtonText: {
    color: registerColors.accent,
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.bold,
    letterSpacing: 0.5,
  },
  socialFollowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    paddingVertical: 2,
  },
  // Small app-version label. Uses a monospace face (not the default sans-serif)
  // to read like a build tag.
  versionText: {
    textAlign: 'center',
    color: registerColors.gray,
    fontSize: 11,
    letterSpacing: 0.5,
    fontFamily: Platform.select({ ios: 'Courier New', android: 'monospace' }),
  },
  officialLoginSection: {
    alignItems: 'center',
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  officialLoginDivider: {
    width: '100%',
    height: 1,
    backgroundColor: registerColors.grayLight,
    marginBottom: spacing.xs,
  },
  officialLoginTitle: {
    color: registerColors.text,
    fontSize: fontSizes.lg,
    fontWeight: '800',
    letterSpacing: 0.4,
    lineHeight: 22,
    textAlign: 'center',
  },
  officialLoginSubtitle: {
    color: registerColors.textLight,
    fontSize: fontSizes.md,
    lineHeight: 20,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  legalModalSheet: {
    backgroundColor: registerColors.white,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    height: '85%',
    paddingBottom: spacing.xl,
  },
  legalModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: registerColors.grayLight,
  },
  legalModalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: registerColors.text,
  },
  settingsLegalModalHeader: {
    justifyContent: 'center',
    borderBottomWidth: 0,
  },
  settingsLegalModalTitle: {
    width: '100%',
    textAlign: 'center',
  },
  legalModalScroll: {
    flex: 1,
  },
  legalModalScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  legalModalBody: {
    fontSize: fontSizes.sm,
    color: registerColors.textLight,
    lineHeight: 22,
  },
  legalModalScrollAnchor: {
    height: 1,
  },
  legalScrollHint: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.xs,
  },
  legalScrollHintText: {
    fontSize: fontSizes.xs,
    color: registerColors.gray,
  },
  legalAcceptButton: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    backgroundColor: registerColors.accent,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  settingsLegalCloseButton: {
    backgroundColor: themeColors.navigationActive,
    borderRadius: radius.md,
  },
  legalAcceptButtonDisabled: {
    backgroundColor: registerColors.grayLight,
  },
  legalAcceptButtonText: {
    color: registerColors.white,
    fontSize: fontSizes.md,
    fontWeight: '700',
  },
  legalAcceptButtonTextDisabled: {
    color: registerColors.gray,
  },
});
