import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes, radius, spacing } from '../theme';

/** Shared palette for the report step flow (aligned with register tokens). */
export const reportColors = {
  primary: colors.navigationActive,
  primaryLight: colors.primaryLight,
  accent: '#FF7657',
  success: colors.success,
  text: '#1C2B4B',
  textLight: '#5A6A85',
  white: colors.white,
  border: colors.border,
  track: '#E4EAF5',
};

export const reportStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(8, 20, 43, 0.66)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  overlayDismissArea: {
    ...StyleSheet.absoluteFill,
  },
  keyboardHost: {
    width: '100%',
    maxWidth: 440,
    maxHeight: '92%',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    width: '100%',
    maxHeight: '100%',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    shadowColor: '#07152E',
    shadowOpacity: 0.26,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  cardCompact: {
    maxHeight: '96%',
  },
  headerContainer: {
    paddingTop: 18,
    backgroundColor: colors.navigationActive,
  },
  headerContainerCompact: {
    paddingTop: 12,
  },

  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    marginBottom: 12,
  },
  headerRowCompact: {
    marginBottom: 8,
  },
  deliveredCloseButton: {
    width: 40,
    height: 40,
    marginRight: -8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flexShrink: 1,
    fontFamily: fonts.bold,
    fontSize: 22,
    color: reportColors.white,
    letterSpacing: -0.5,
  },

  // --- Progress ---
  progressWrap: {
    paddingHorizontal: spacing.xl,
    marginBottom: 8,
  },
  progressSteps: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressConnector: {
    width: 35,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  progressConnectorActive: {
    backgroundColor: 'rgba(255,255,255,0.68)',
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.34)',
  },
  progressDotComplete: {
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  progressDotCurrent: {
    width: 22,
    height: 22,
    backgroundColor: reportColors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDotText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.xs,
    color: colors.navigationActive,
  },
  progressLabel: {
    marginTop: 7,
    textAlign: 'center',
    fontFamily: fonts.semibold,
    fontSize: 13,
    color: reportColors.white,
    letterSpacing: 0.2,
  },
  emergencyBanner: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: 9,
  },
  emergencyBannerText: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#FF9A82',
  },
  contentPanel: {
    flexShrink: 1,
    overflow: 'hidden',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: colors.white,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
  },
  contentPanelCompact: {
    paddingTop: 9,
    paddingBottom: 9,
  },

  // --- Step shell ---
  // No fixed minHeight: the scroll area hugs the step's content so the modal
  // never shows dead space below the footer button. The card's maxHeight
  // (90%) still caps it on small screens, where the content scrolls.
  stepHost: {
    flexGrow: 0,
  },
  stepHostContent: {
    paddingBottom: spacing.xs,
  },
  stepContent: {
    width: '100%',
  },
  stepTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  stepTitle: {
    flexShrink: 1,
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    color: reportColors.text,
  },
  stepSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: reportColors.textLight,
    lineHeight: 20,
    marginBottom: spacing.sm,
  },

  // --- Location step ---
  locationIntro: {
    marginBottom: spacing.sm,
  },
  residentStepTitle: {
    fontFamily: fonts.bold,
    fontSize: 26,
    lineHeight: 30,
    letterSpacing: -0.65,
    color: reportColors.text,
  },
  residentStepSubtitle: {
    marginTop: 3,
    marginBottom: 6,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 19,
    color: '#31558B',
  },
  locationCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  pulseStage: {
    width: 120,
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: reportColors.primary,
  },
  pinBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: reportColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationLabel: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: reportColors.text,
    textAlign: 'center',
  },
  locationHint: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: reportColors.textLight,
    textAlign: 'center',
  },
  locationErrorText: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: reportColors.accent,
    textAlign: 'center',
  },
  locationActions: {
    width: '100%',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  locationReadyContent: {
    gap: spacing.sm,
  },
  locationSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: '#F3F7FD',
    padding: spacing.md,
  },
  locationIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.navigationActive,
  },
  locationSummaryCopy: {
    flex: 1,
    gap: 2,
  },
  locationSummaryLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    color: reportColors.textLight,
  },
  locationSummaryValue: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    lineHeight: 19,
    color: reportColors.text,
  },
  accuracyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  accuracyText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    color: reportColors.text,
  },
  locationWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: '#FFF1ED',
    padding: spacing.sm,
  },
  locationWarningText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    lineHeight: 17,
    color: '#A7432C',
  },
  locationLimitText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    lineHeight: 18,
    color: reportColors.textLight,
  },
  adjustPinButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: '#CAD6E8',
    borderRadius: radius.md,
    paddingVertical: 12,
    backgroundColor: colors.white,
  },
  adjustPinButtonText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: reportColors.primary,
  },
  residentLocationLoading: {
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  residentMapCard: {
    position: 'relative',
    height: 310,
    marginBottom: 7,
    overflow: 'hidden',
    borderRadius: 13,
    backgroundColor: '#EAF3F6',
  },
  mapPreview: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    backgroundColor: '#EAF3F6',
  },
  mapPreviewCompact: {
    width: 116,
    height: 76,
    borderRadius: 10,
  },
  mapPreviewWebView: {
    flex: 1,
    backgroundColor: '#EAF3F6',
  },
  mapCenterMarker: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 56,
    height: 56,
    marginLeft: -28,
    marginTop: -52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapCenterMarkerCompact: {
    width: 38,
    height: 38,
    marginLeft: -19,
    marginTop: -35,
  },
  mapCenterMarkerOutline: {
    position: 'absolute',
  },
  mapPreviewLoading: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDF5F7',
  },
  mapPreviewFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: '#EDF5F7',
  },
  mapPreviewFallbackText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    color: reportColors.textLight,
  },
  residentAccuracyPill: {
    position: 'absolute',
    top: 13,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.96)',
    shadowColor: '#0F2044',
    shadowOpacity: 0.13,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    maxWidth: '82%',
  },
  residentAccuracyPillText: {
    flexShrink: 1,
    fontFamily: fonts.semibold,
    fontSize: 10,
    color: reportColors.primary,
  },
  residentAddressCard: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 15,
    paddingVertical: 13,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.97)',
    shadowColor: '#0F2044',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  residentAddressIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: reportColors.primary,
  },
  residentAddressCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  residentAddressPrimary: {
    fontFamily: fonts.bold,
    fontSize: 15,
    color: reportColors.text,
  },
  residentAddressSecondary: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#31558B',
  },
  residentBarangayPickerOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 50,
    elevation: 50,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
  },
  residentBarangayPickerBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(8, 20, 43, 0.64)',
  },
  residentBarangayPickerCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '72%',
    overflow: 'hidden',
    borderRadius: 16,
    backgroundColor: colors.white,
    shadowColor: '#07152E',
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  residentBarangayPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.border,
  },
  residentBarangayPickerHeading: {
    flex: 1,
    gap: 3,
  },
  residentBarangayPickerTitle: {
    fontFamily: fonts.bold,
    fontSize: 20,
    color: reportColors.text,
  },
  residentBarangayPickerSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
    color: reportColors.textLight,
  },
  residentBarangayPickerClose: {
    width: 40,
    height: 40,
    marginTop: -5,
    marginRight: -5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  residentBarangayPickerList: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  residentBarangayPickerOption: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 9,
  },
  residentBarangayPickerOptionSelected: {
    backgroundColor: reportColors.primaryLight,
  },
  residentBarangayPickerOptionIcon: {
    width: 31,
    height: 31,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#E5EEFC',
  },
  residentBarangayPickerOptionText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 14,
    color: reportColors.text,
  },
  residentBarangayPickerOptionTextSelected: {
    fontFamily: fonts.bold,
    color: reportColors.primary,
  },
  residentBarangayPickerState: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.lg,
  },
  residentBarangayPickerStateText: {
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    color: reportColors.textLight,
  },
  residentBarangayPickerRetry: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: 8,
    backgroundColor: reportColors.primary,
  },
  residentBarangayPickerRetryText: {
    fontFamily: fonts.semibold,
    fontSize: 13,
    color: reportColors.white,
  },
  residentInlineWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginBottom: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 9,
    backgroundColor: '#FFF0EC',
  },
  residentInlineWarningText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 16,
    color: '#9D3F2A',
  },
  residentPinAdjustmentActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  residentPinAdjustmentActionsLargeText: {
    flexDirection: 'column',
  },
  residentPinAdjustmentButton: {
    flex: 1,
    minHeight: 48,
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
  },
  residentPinAdjustmentButtonLargeText: {
    width: '100%',
    flex: 0,
  },
  residentAdjustButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  residentAdjustButtonText: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: reportColors.primary,
  },
  residentAdjustmentText: {
    marginTop: -6,
    marginBottom: 5,
    textAlign: 'center',
    fontFamily: fonts.regular,
    fontSize: 10,
    color: reportColors.textLight,
  },

  // --- Inputs (details) ---
  incidentTypeGrid: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: spacing.xs,
  },
  incidentTypeOption: {
    flex: 1,
    minHeight: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: radius.md,
    paddingHorizontal: 2,
    backgroundColor: colors.white,
  },
  incidentTypeOptionSelected: {
    borderColor: colors.navigationActive,
    backgroundColor: colors.navigationActive,
  },
  incidentTypeOptionText: {
    fontFamily: fonts.medium,
    fontSize: 9,
    lineHeight: 12,
    textAlign: 'center',
    color: reportColors.text,
  },
  incidentTypeOptionTextSelected: {
    color: reportColors.white,
  },
  pinConfirmedText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.xs,
    color: reportColors.success,
    marginBottom: spacing.sm,
  },
  barangaySelectBox: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: radius.md,
    overflow: 'hidden',
    marginBottom: spacing.xs,
  },
  barangayOption: {
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.border,
    backgroundColor: colors.white,
  },
  barangayOptionSelected: {
    backgroundColor: reportColors.primaryLight,
  },
  barangayOptionText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: reportColors.text,
  },
  barangayOptionTextSelected: {
    fontFamily: fonts.semibold,
    color: reportColors.text,
  },
  barangayLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  barangayHelperText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: reportColors.textLight,
  },
  barangayErrorBlock: {
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  label: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: reportColors.text,
  },
  labelOptional: {
    fontFamily: fonts.regular,
    color: reportColors.textLight,
  },
  input: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    color: reportColors.text,
    backgroundColor: colors.white,
  },
  textArea: {
    minHeight: 96,
  },
  gpsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: reportColors.primaryLight,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xs,
  },
  gpsText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: reportColors.text,
  },
  residentFieldLabel: {
    marginTop: 8,
    marginBottom: 4,
    fontFamily: fonts.bold,
    fontSize: 13,
    color: reportColors.text,
  },
  residentOptionalText: {
    fontFamily: fonts.regular,
    color: '#466B9F',
  },
  residentIncidentTypeGrid: {
    flexDirection: 'row',
    gap: 7,
  },
  residentIncidentTypeGridLargeText: {
    flexDirection: 'column',
  },
  residentIncidentTypeOption: {
    flex: 1,
    minWidth: 0,
    minHeight: 61,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    borderWidth: 1,
    borderColor: '#D8E2F0',
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  residentIncidentTypeOptionLargeText: {
    width: '100%',
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  residentIncidentTypeOptionSelected: {
    borderColor: reportColors.primary,
    backgroundColor: reportColors.primary,
    shadowColor: '#0F2044',
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  residentIncidentTypeText: {
    maxWidth: '95%',
    textAlign: 'center',
    fontFamily: fonts.bold,
    fontSize: 10,
    lineHeight: 12,
    color: reportColors.text,
  },
  residentIncidentTypeTextLargeText: {
    flex: 1,
    maxWidth: undefined,
    textAlign: 'left',
  },
  residentIncidentTypeTextSelected: {
    color: reportColors.white,
  },
  residentInput: {
    minHeight: 45,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 11,
    backgroundColor: '#EEF5FF',
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 19,
    color: reportColors.text,
  },
  residentTextArea: {
    minHeight: 74,
  },
  residentBarangayState: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 7,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    backgroundColor: '#FFF5EF',
  },
  residentBarangayStateText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 11,
    color: reportColors.textLight,
  },
  residentRetryText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: reportColors.primary,
  },

  // --- Attachments ---
  counterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  counterText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: reportColors.textLight,
  },
  counterOver: {
    color: reportColors.accent,
  },
  mediaActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  mediaButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: radius.md,
    paddingVertical: 12,
  },
  mediaButtonDisabled: {
    opacity: 0.5,
  },
  mediaButtonText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: reportColors.primary,
  },
  mediaList: {
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  mediaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: radius.md,
    padding: spacing.sm,
  },
  thumb: {
    width: 44,
    height: 44,
    borderRadius: radius.sm,
    backgroundColor: reportColors.track,
  },
  videoThumb: {
    width: 44,
    height: 44,
    borderRadius: radius.sm,
    backgroundColor: reportColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaChipLabel: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm,
    color: reportColors.text,
  },
  residentPhotoAction: {
    height: 134,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    marginBottom: 7,
    borderRadius: 10,
    backgroundColor: '#EAF2FF',
  },
  residentCameraCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: reportColors.primary,
  },
  residentCaptureLabel: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: reportColors.text,
  },
  residentVideoAction: {
    minHeight: 49,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: 12,
    borderRadius: 8,
    backgroundColor: '#EAF2FF',
  },
  residentVideoActionText: {
    fontFamily: fonts.semibold,
    fontSize: 13,
    color: reportColors.primary,
  },
  residentEvidenceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  residentEvidenceTitle: {
    flexShrink: 1,
    fontFamily: fonts.bold,
    fontSize: 13,
    color: reportColors.text,
  },
  residentEvidenceCount: {
    fontFamily: fonts.bold,
    fontSize: 12,
    color: reportColors.text,
  },
  residentEvidenceRow: {
    gap: 8,
    paddingRight: 2,
    paddingBottom: 10,
  },
  residentEvidenceCard: {
    position: 'relative',
    width: 145,
    height: 103,
    overflow: 'hidden',
    borderRadius: 11,
    backgroundColor: reportColors.primary,
  },
  residentEvidenceImage: {
    width: '100%',
    height: '100%',
  },
  residentEvidenceVideo: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#243B66',
  },
  residentVideoDuration: {
    position: 'absolute',
    right: 7,
    bottom: 6,
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: reportColors.white,
  },
  residentRemoveEvidence: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
  },
  residentEvidenceEmpty: {
    height: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 11,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#CDD8E8',
    backgroundColor: '#F8FAFD',
    marginBottom: 10,
  },
  residentEvidenceEmptyText: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: reportColors.textLight,
  },

  // --- Media preview ---
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  previewContent: {
    width: '100%',
    aspectRatio: 3 / 4,
    maxHeight: '80%',
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  previewVideo: {
    width: '100%',
    height: '100%',
  },
  previewClose: {
    position: 'absolute',
    top: spacing.xl,
    right: spacing.lg,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },

  // --- Review ---
  reviewTimeline: {
    position: 'relative',
    gap: 14,
    marginTop: 5,
    marginBottom: 8,
  },
  reviewTimelineLine: {
    position: 'absolute',
    top: 28,
    bottom: 34,
    left: 17,
    width: 1,
    backgroundColor: '#C9D8EC',
  },
  reviewSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  reviewTimelineIcon: {
    zIndex: 1,
    width: 35,
    height: 35,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.navigationActive,
  },
  reviewSectionBody: {
    flex: 1,
    minHeight: 44,
    minWidth: 0,
  },
  reviewSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    minHeight: 20,
    marginBottom: 5,
  },
  reviewSectionHeaderLargeText: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  reviewSectionTitle: {
    fontFamily: fonts.semibold,
    fontSize: 13,
    color: reportColors.text,
    flexShrink: 1,
  },
  reviewEditText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: '#0D63E5',
  },
  reviewEditButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    marginHorizontal: -spacing.sm,
  },
  reviewTypeText: {
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
    fontFamily: fonts.semibold,
    fontSize: 12,
    color: reportColors.text,
  },
  reviewPrimaryText: {
    fontFamily: fonts.semibold,
    fontSize: 13,
    lineHeight: 18,
    color: reportColors.text,
  },
  reviewSecondaryText: {
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
    color: '#31558B',
  },
  reviewAdjustmentText: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: 10,
    color: reportColors.textLight,
  },
  reviewLocationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  reviewLocationRowLargeText: {
    flexDirection: 'column',
  },
  reviewLocationCopy: {
    flex: 1,
  },
  reviewMediaRow: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 5,
  },
  reviewMediaThumb: {
    flex: 1,
    height: 67,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: reportColors.track,
  },
  reviewMediaImage: {
    width: '100%',
    height: '100%',
  },
  reviewVideoThumb: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.navigationActive,
  },
  reviewVideoDuration: {
    position: 'absolute',
    right: 6,
    bottom: 4,
    fontFamily: fonts.semibold,
    fontSize: 9,
    color: colors.white,
  },
  reviewAccuracyNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: reportColors.primaryLight,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 7,
  },
  reviewAccuracyText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 11,
    color: reportColors.primary,
  },
  // --- Buttons / footer ---
  privacyNotice: {
    marginTop: spacing.md,
    fontFamily: fonts.regular,
    fontSize: fontSizes.xs,
    color: reportColors.textLight,
    lineHeight: 16,
  },
  errorText: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: reportColors.accent,
    marginBottom: spacing.xs,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.navigationActive,
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  residentPrimaryButton: {
    flex: 0,
    width: '100%',
    minHeight: 48,
    borderRadius: 8,
    marginTop: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.white,
  },
  secondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: reportColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: reportColors.textLight,
  },

  // --- Success ---
  successCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  checkCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: reportColors.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryCircle: {
    backgroundColor: reportColors.primary,
  },
  deliveryCircleNotSent: {
    backgroundColor: '#D15A3A',
  },
  successTitle: {
    fontFamily: fonts.bold,
    fontSize: 22,
    color: reportColors.text,
    textAlign: 'center',
  },
  successAddress: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: reportColors.textLight,
    textAlign: 'center',
    lineHeight: 20,
  },
  deliveryStatusMessage: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: reportColors.textLight,
    textAlign: 'center',
    lineHeight: 20,
  },
});
