import { StyleSheet } from 'react-native';

import { colors, fonts, fontSizes, radius, spacing } from '../theme';

export const notificationColors = {
  unread: '#F1F6FD',
  divider: '#EEF0F4',
  actionRead: '#3976B7',
  actionDelete: '#C33F4A',
  verified: '#2F669A',
  verifiedSoft: '#E2EDF8',
  comment: '#507EAE',
  commentSoft: '#E9F1FA',
  upvote: '#244F7D',
  upvoteSoft: '#E5EDF7',
  warning: '#6A86A8',
  warningSoft: '#EDF3FA',
};

export const notificationStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: notificationColors.divider,
  },
  backButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
  },
  title: {
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: fontSizes.xl,
    color: colors.text,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: spacing.xxl,
  },
  section: {
    paddingTop: spacing.lg,
  },
  sectionTitle: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    fontFamily: fonts.bold,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  row: {
    flex: 1,
    minWidth: 0,
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: notificationColors.divider,
    backgroundColor: colors.white,
  },
  rowUnread: {
    backgroundColor: notificationColors.unread,
  },
  rowHighlighted: {
    marginHorizontal: spacing.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: radius.sm,
  },
  swipeContainer: {
    backgroundColor: colors.white,
  },
  swipeContent: {
    backgroundColor: colors.white,
  },
  swipeActions: {
    width: 196,
    flexDirection: 'row',
  },
  swipeAction: {
    width: 98,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: notificationColors.divider,
  },
  swipeReadText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xs,
    color: notificationColors.actionRead,
    textAlign: 'center',
  },
  swipeDeleteText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xs,
    color: notificationColors.actionDelete,
    textAlign: 'center',
  },
  avatarWrap: {
    width: 46,
    height: 46,
  },
  avatar: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: colors.primaryLight,
  },
  avatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes.md,
    color: colors.navigationActive,
  },
  typeBadge: {
    position: 'absolute',
    right: -2,
    bottom: -1,
    width: 21,
    height: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.white,
  },
  copy: {
    flex: 1,
    minWidth: 0,
  },
  messageLine: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.md,
    lineHeight: 21,
    color: colors.text,
  },
  messageTitle: {
    fontFamily: fonts.semibold,
  },
  time: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    color: colors.textMuted,
  },
  unreadDot: {
    width: 10,
    height: 10,
    flexShrink: 0,
    marginTop: 6,
    borderRadius: 5,
    backgroundColor: '#E14348',
  },
  popupLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    zIndex: 100,
    elevation: 20,
  },
  popupPosition: {
    paddingHorizontal: spacing.md,
  },
  popupCard: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    shadowColor: colors.navigationActive,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  popupChevron: {
    flexShrink: 0,
    marginTop: 10,
  },
  retryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.primaryLight,
  },
  retryText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm,
    color: colors.navigationActive,
  },
  state: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
  },
  stateIcon: {
    width: 62,
    height: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 31,
    backgroundColor: colors.primaryLight,
  },
  stateTitle: {
    marginTop: spacing.sm,
    fontFamily: fonts.bold,
    fontSize: fontSizes.lg,
    color: colors.text,
    textAlign: 'center',
  },
  stateBody: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm,
    lineHeight: 20,
    color: colors.textMuted,
    textAlign: 'center',
  },
});
